### ISSUE TITLE
Deprecate redundant singleuser_ prefix on config

### ISSUE THREAD

**Issue by minrk** [jupyterhub/kubespawner#101]
when configuring the Spawner, several traits have a `singleuser_` prefix. This is mostly redundant with the fact that a Spawner is all about configuring a singleuser server. Most (probably all) of these should be deprecated in favor of the same name without `singleuser_`. The `singleuser_` names can be kept as a deprecated alias from config to avoid breaking existing config.

**Comment by minrk** [comment]
The same probably goes for the few `user_` traits, where `user` is a synonym for `singleuser`.

**Comment by yuvipanda** [comment]
I agree.
