### ISSUE TITLE
Accessible URL not set

### ISSUE THREAD

**Issue by jkinkead** [jupyterhub/kubespawner#107]
PR #83 introduced an error when it removed [the override of get_env](https://github.com/Analect/kubespawner/blob/d09c6956f1530eeba2bed85dac8253739745c134/kubespawner/spawner.py#L858-L869). Formerly, this was used to communicate the accessible hub URL via the `JUPYTERHUB_API_URL` environment variable. Now, this relies on [the base implementation's `JUPYTERHUB_API_URL` value](https://github.com/jupyterhub/jupyterhub/blob/ee76772e1ba1e57bcac412bded650b8a4a67f0e4/jupyterhub/spawner.py#L558), which is incorrect.

It seems like the `get_env` override needs to be retained, at least for the API URL?

**Comment by yuvipanda** [comment]
@jkinkead can you tell me what you mean by it is incorrect? With JupyterHub 0.8, there's also a `c.JupyterHub.hub_connect_ip` and `c.JupyterHub.hub_connect_port`, which when set should make the URL accurate.

**Comment by jkinkead** [comment]
Interesting. Let me try setting those - they weren't working when I tried earlier.

**Comment by jkinkead** [comment]
I *think* the problem I'm having is the fact that the hub is using the `hub_connect_ip` value both for passing to the spawners (good) but also for configuring the routes on the proxy (bad).

This results in a configuration like:

k8s service URL -> proxy API default path
proxy API port default path -> k8s service URL

which seems to be causing timeouts.

**Comment by yuvipanda** [comment]
@jkinkead hmm, is the proxy not able to connect to the hub's service IP? That is how we configure it in the helm chart at http://github.com/jupyterhub/zero-to-jupyterhub-k8s (see https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/images/hub/jupyterhub_config.py#L126) and it seems to work.

**Comment by jkinkead** [comment]
Ahh. It turns out this was actually an issue with our Flannel configuration; we don't support "hairpin" routes (routing from a pod, through a service, and back through the pod).

My mistake - everything is working correctly now!

(although it does draw attention to the fact that having only one configuration point for this results in some weird network behavior if the proxy is run alongside the hub process)
