### ISSUE TITLE
Allow launching user-based images

### ISSUE THREAD

**Issue by jkinkead** [jupyterhub/kubespawner#108]
This is related to #75 & #79 .

We would like to be able to launch a singleuser image that varies based on the authenticated user.

I like the ideas presented in #79 around having a ConfigMap that stores a userId -> option mapping, with a selector presented to the user.

As a stopgap, having `singleuser_image_spec` accept a Callable value taking the `user` object would be sufficient.

This is something that I will likely have time to work on implementing in the coming months.

**Comment by jkinkead** [comment]
Also issue #94 , which has the well-enumerated list of work items that could support this. :)

**Comment by sherl0cks** [comment]
I'm very keen on this feature. It's a requirement for the enterprise environment I'm currently working in, and I'd be interesting in collaborating on a solution.

I like the idea of allowing uses to select from a list of options when they spawn their server and then storing the results in a `ConfigMap`. I wonder how would that list of options would be created? Perhaps labeling images and then querying the `Image` k8s API?

**Comment by clkao** [comment]
@sherl0cks you can look at the ProfilesSpawner in https://github.com/jupyterhub/wrapspawner

if you authenticator can store scope as privilege, you can also adjust the allowed item in the list accordingly.

**Comment by sherl0cks** [comment]
@clkao thank you for sharing. wrapspawner does look interesting, I'll give it a go and report back. if wrapspawner is the direction to go here, it would probably be best to close this issue.

**Comment by jkinkead** [comment]
We ended up using a solution based on wrapspawner - thanks for the link!

I'm closing this issue for now.
