### ISSUE TITLE
Jupyter notebook timedout

### ISSUE THREAD

**Issue by madanam1** [jupyterhub/kubespawner#119]
Hi,

 Thanks for the nice plugin.  I have integration with AD and it works fine. 
When starting the notebook server the notebook and associated PVC is created, but the notebook gets destroyed with below error:

Error:
----
 | Traceback (most recent call last):
  | File "/opt/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1511, in _execute
  | result = yield result
  | File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 720, in get
  | yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), spawner._spawn_future)
  | File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
  | yield spawn_future
  | File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 476, in spawn
  | raise e
  | File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/user.py", line 450, in spawn
  | resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
  | File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
  | timeout=timeout
  | File "/opt/anaconda3/lib/python3.6/site-packages/jupyterhub/utils.py", line 135, in exponential_backoff
  | raise TimeoutError(fail_message)
  | TimeoutError: Server at http://10.1.2.123:8888/user/xxxxxxx/ didn't respond in 30 secon

Jupyter-notebook container logs:
----------------------------------

[I 16:53:32.989 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
--
  | [I 16:53:33.053 NotebookApp] JupyterLab alpha preview extension loaded from /opt/anaconda3/lib/python3.6/site-packages/jupyterlab
  | JupyterLab v0.27.0
  | Known labextensions:
  | [I 16:53:33.055 NotebookApp] Running the core application with no additional extensions or settings
  | [I 16:53:33.057 NotebookApp] Serving notebooks from local directory: /opt/anaconda3/bin
  | [I 16:53:33.057 NotebookApp] 0 active kernels
  | [I 16:53:33.057 NotebookApp] The Jupyter Notebook is running at:
  | [I 16:53:33.058 NotebookApp] http://localhost:8888/?token=41696518f735c0a1ea60d0cc4bf7b5ea52e84ceea602d401
  | [I 16:53:33.058 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
  | [C 16:53:33.058 NotebookApp]
  |  
  | Copy/paste this URL into your browser when you connect for the first time,
  | to login with a token:
  | http://localhost:8888/?token=41696518f735c0a1ea60d0cc4bf7b5ea52e84ceea602d401

Jupyterhub_config.py Config: 

import os
c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'

c.JupyterHub.ip = '0.0.0.0'
c.JupyterHub.hub_ip = '0.0.0.0'

service_name = os.environ.get('NVS_JUPYTERHUB_SERVICE_NAME', 'nvs-jupyterhub-kubespawn')

# Don't try to cleanup servers on exit - since in general for k8s, we want
# the hub to be able to restart without losing user containers
c.JupyterHub.cleanup_servers = False

# First pulls can be really slow, so let's give it a big timeout
c.KubeSpawner.start_timeout = 60 * 5

# Our simplest user image! Optimized to just... start, and be small!
#c.KubeSpawner.singleuser_image_spec = 'nvs/nvs-jupyter-notebook:v0.1'
c.KubeSpawner.singleuser_image_spec = '172.30.189.95:5000/jhks/nvs-jupyter-notebook:v0.1'

# The spawned containers need to be able to talk to the hub through the proxy!
#c.KubeSpawner.hub_connect_ip = service_name

c.KubeSpawner.singleuser_service_account = 'default'
# Do not use any authentication at all - any username / password will work.
#c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'

# The spawned containers need to be able to talk to the hub through the proxy!
#c.KubeSpawner.hub_connect_ip = os.environ['NVS_JUPYTERHUB_KUBESPAWN_SERVICE_HOST']
#c.JupyterHub.hub_connect_ip = os.environ['NVS_JUPYTERHUB_KUBESPAWN_SERVICE_HOST']

c.KubeSpawner.user_storage_pvc_ensure = True

c.JupyterHub.allow_named_servers = True
c.KubeSpawner.volumes = [
     {
         'name': 'pvc-jupyter-home',
         'persistentVolumeClaim': {
             'claimName': 'pvc-jupyter-home'
         }
     }
 ]

c.KubeSpawner.volume_mounts = [
     {
         'name': 'pvc-jupyter-home',
         'mountPath': '/home'
         }
 ]

--
Am I doing something wrong.

Any help much appreciated.

Regards,
Amar.

**Comment by Jameshzc** [comment]
Hi, madanam1, have you fixed this problem?  I just met the same problem.
