### ISSUE TITLE
How is the performance of this spawner?

### ISSUE THREAD

**Issue by forbxy** [jupyterhub/kubespawner#120]
swarmspawner started the container has been slower than dockerspawner 5s to start a user's notebook。
how about the kubespawner?

**Comment by yuvipanda** [comment]
Can you explain a bit more what kinda performance you are looking for?

**Comment by forbxy** [comment]
The time it takes to start user service；
 thank u，I test it after ask this question,  k8s work good。
we  used swarm mode， it is slow and always takes 7-8 seconds to start a user service

**Comment by gsemet** [comment]
When using the prepuller the service starts arround 5s max, which is totally acceptable

**Comment by consideRatio** [comment]
KubeSpawner is in practice just sending a request to a k8s api-server, and then then the kubernetes cluster is responsible for creating the pod. I estimate this takes ~2-3 seconds for fast kubernetes clusters. If the pod is mounting persistent disks etc it can be slower and take ~20 seconds for example.
