### ISSUE TITLE
terminating pod not reflected

### ISSUE THREAD

**Issue by clkao** [jupyterhub/kubespawner#131]
If I stop my server and try to start immediately, I get "you server is starting up" until the pod is really terminated.  I am using the profilesspawner, the dropdown menu shows after the message disappears.

**Comment by consideRatio** [comment]
I think this may be a JupyterHub issue rather than a KubeSpawner issue, but if it is a KubeSpawner issue, i think we need to get this issue better documented because I end up feeling inactionable at this point - closing as potentially not relevant to KubeSpawner and stale.
