### ISSUE TITLE
support runAsUser securityContext

### ISSUE THREAD

**Issue by yee379** [jupyterhub/kubespawner#140]
we i currently use jupyterhub to spawn off kubernetes pods. i inject the spawner with UID and GID information from our ldap and basically 'trust' that the pod will do the right thing and switch to the UID and GID specified.

it would be better, imo, to support the pod based `runAsUser` k8s `securityContext` as per [configure-pod-container](https://raw.githubusercontent.com/kubernetes/website/master/docs/tasks/configure-pod-container/security-context-2.yaml). i'm not really sure how one could manage the gids this way tho.

**Comment by yuvipanda** [comment]
You can currently do this by setting `c.KubeSpawner.singleuser_uid`, which sets `runAsUser`. Does that not do what you want?

You can also set gids with `c.KubeSpawner.singleuser_fsgid` and `c.KubeSpawner.singleuser_supplemental_gids`, but would need to make sure you have appropriate entries in your container's `/etc/group` file.

Feel free to re-open if I've misunderstood the issue!

**Comment by Falven** [comment]
It's broken. Doesn't work for mounts.
