### ISSUE TITLE
c.KubeSpawner.default_url = '/lab' is correct?

### ISSUE THREAD

**Issue by lfzyx** [jupyterhub/kubespawner#149]
I set` c.KubeSpawner.default_url = '/lab'`, but when I login from hub , the default url still is `/tree`.

Other configuration:

```
c.KubeSpawner.singleuser_image_spec = 'jupyterhub/singleuser:latest'

c.KubeSpawner.singleuser_service_account = 'default'

c.JupyterHub.allow_named_servers = True
```

**Comment by lfzyx** [comment]
I see the difference between KubeSpawner and dockerspawner 

KubeSpawner

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4372   740 ?        Ss   02:25   0:00 tini -- start-notebook.sh
root         7  0.0  0.0  47012  3612 ?        S    02:25   0:00 sudo -E -H -u jovyan PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PYTHONPATH= jupyterhub-singleuser --ip=0.0.0.0
jovyan      17  0.0  0.1 283972 61840 ?        Sl   02:25   0:01 /opt/conda/bin/python /opt/conda/bin/jupyterhub-singleuser --ip=0.0.0.0
root        65  0.0  0.0  19928  3860 ?        Ss   02:35   0:00 bash
root        96  0.0  0.0  36088  3212 ?        R+   03:27   0:00 ps aux
```


dockerspawner

```
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
jovyan        1  0.0  0.0   4368   656 ?        Ss   Mar21   0:01 tini -- start-notebook.sh --ip="0.0.0.0" --port=8888 --notebook-dir="/home/jovyan/work" --NotebookApp.default_url="/lab"
jovyan        7  0.0  0.7 656340 64496 ?        Sl   Mar21   0:13 /opt/conda/bin/python /opt/conda/bin/jupyterhub-singleuser --ip="0.0.0.0" --port=8888 --notebook-dir="/home/jovyan/work" --NotebookApp.default_url="/lab"
jovyan       29  0.0  0.5 632156 43680 ?        Ssl  Mar21   0:03 /opt/conda/bin/python -m ipykernel_launcher -f /home/jovyan/.local/share/jupyter/runtime/kernel-eeaebb52-c6ed-47e4-a295-8784ed59cb4e.json
jovyan       32  0.0  0.5 632800 44232 ?        Ssl  Mar21   0:03 /opt/conda/bin/python -m ipykernel_launcher -f /home/jovyan/.local/share/jupyter/runtime/kernel-b5a5610d-ce6b-441a-b208-5f67fdd6593b.json
jovyan       82  0.0  0.0  19928  3680 pts/0    Ss   02:33   0:00 bash
jovyan      103  0.0  0.0  36084  3160 pts/0    R+   03:27   0:00 ps aux
```

**Comment by gweis** [comment]
Workaround:

Looking at the code here https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L1159 , you can see that `self.get_args()` is only called when `self.cmd` is set. For a standard jupyter notebook image it is enough to set it it `KubeSpawner.cmd=['start-notebook.sh']`. With this set, you'll get the same arguments set as with `DockerSpawner`.

I guess this check is there to avoid overriding the default `CMD` set in the docker image, but some documentation or maybe even setting it to a default value used with the Jupiter/docker-stack images would be useful. Even if it is to force a user to change it when needed.

**Comment by gweis** [comment]
I am using custom docker images as well, but I went with the startup scripts from https://github.com/jupyter/docker-stacks/tree/master/base-notebook
and put my custom start-up scripts into `/usr/local/bin/start-notebook.d` (loaded here https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh#L39)

Just be careful with scripts in that folder as scripts ending with .sh will be sourced and all other executable file will run in a sub shell.

I guess most of the documentation and examples are tied to the entry point scripts provided by the docker-stacks images.

**Comment by consideRatio** [comment]
Hmmm I dont understand why, but perhaps you need to set c.Spawner.default_url rather than c.KubeSpawner.defualt_url? I recall some issue with this myself that i never grasped.

PS: this may be useful to have watched to better grasp whats going om: https://m.youtube.com/watch?v=_gYEVTaNuKU


See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/images/hub/jupyterhub_config.py

**Comment by dkipping** [comment]
Thank you both for your feedback!

@gweis That is amazign. I didn't read the scripts careful enough to know that this is possible. Hopefully that already simplifies the image and script and makes the jupyterlab thing work

@consideRatio Thanks for the resources! Yeah I already tried setting the attributes on my custom spawner and directly on the spawner class. I think the entrypoint script was blocking it. Will have a look, what is the easiest/most intuitive way to make it work now.

**Comment by dkipping** [comment]
UPDATE:

So the method as suggested by gweis works, then the Spawner.default_url and the Spawner.cmd.

However this is not working out of the box when you try to grant sudo to the users.

Referring to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/562, you would have to set
```
singleuser:
  uid: 0
```

which results in the following error:
```
[C 2019-01-11 13:58:06.816 SingleUserNotebookApp notebookapp:1707]Running as root is not recommended. Use --allow-root to bypass.
```

Following the tip to set:
```
singleuser:
  cmd: null
```

as provided in the thread (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/562#issuecomment-447123342) is not an option, as setting `jupyter-labhub` is required to be set in the spawner settings.

Guess one would have to fall back to provide the sudo rights in our custom image as proposed in the same thread:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/562#issuecomment-372440003

**Comment by consideRatio** [comment]
This issue is quite old and many things have changed since it was written, but to summarize.

- `singleuser.defaultUrl` is the z2jh helm chart config to set `c.Spawner.default_url`
- `jupyter-labhub` should no longer be used

**Comment by JacoGasp** [comment]
I still face this issue. 
For me `c.KubeSpawner.default_url` has no effect whatever url I set (/notebooks, /lab...)

**Comment by yuvipanda** [comment]
If you were using JupyterHub 2.0, it might be fixed by https://github.com/jupyterhub/jupyterhub/pull/3918 in 2.3.1.
