### ISSUE TITLE
Excessive error messages when spawn timeout

### ISSUE THREAD

**Issue by clkao** [jupyterhub/kubespawner#151]
when a pod can't be spawned within 300s, hub gets 1 `Unhandled error: pod did not start in 300 seconds` and about 18 repeated `Exception in Future` at the same time:

```
Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done
```

This might be actually caused by jupyterhub's `exponential_backoff`.

**Comment by consideRatio** [comment]
If this still is the case, it isn't great, but i don't see a clear technical fix that doesn't introduce a bit too much complexity to avoid it. We want to spot errors, but of course we want to avoid them being overly logged, but how?

I'll go ahead and close this as a bit too stale for me to convert into something actionable.
