### ISSUE TITLE
Infinite "Pending stop" pods

### ISSUE THREAD

**Issue by gsemet** [jupyterhub/kubespawner#158]
Hello. Does anyone already got a pod notebook, from time to time, that seem stuck somehow, andthe hub cannot kill/restart it? I see that from time to time, a given pod of a user seems unkillable by the hub. As an admin, I force stop it, but when the user restart it, it stays always with an error "400 pendning stop".

I need to go on the cluster and kill myself the pod. How can kubespawner handle this case?

**Comment by gsemet** [comment]
Wonder if would not be fixed by #147. Need to test it again...

**Comment by minrk** [comment]
Closing this as potentially fixed by #147 or #174. Feel free to reopen if not.
