### ISSUE TITLE
Allow multiple Kube profile and autoselect a profile based on user profile

### ISSUE THREAD

**Issue by cyberquasar** [jupyterhub/kubespawner#162]
**The requirement**
At my org, I'm required to provide a default container (via jupyterhub) for all users. However, users belonging to certain group may get a GPU container or may be a container with special security privilege allowing them to access data from a secured env or it could be that user will pre qualify to launch a container with 20 GB RAM as opposed to 10 GB (which is default)

**Problem**
While trying to implement above requirement, I found that user attributes retrieved as part of Auth process can not be made available to Spawner until pre_spawn is called. Unfortunately, by then all the decisions about container/pod  spec has already been made. We need a way by which Spawner can have access to user attributes (not just user name) in `KubeSpawner._options_form_default` as well as `KubeSpawner.options_from_form`

**Importance/Criticality**
This feature will help us implement complex ecosystem with flexibility. It is critical from the perspective of accessing secured data. We can have both type of user working through same jupyterhub. 

CC: @yuvipanda @willingc @minrk

**Comment by davidbath** [comment]
Isn't the `user` object available inside the `spawner` class? Once your in to modifying the Kubespawner, I think you should be able retrieve the `auth-state` in the same way as you did in the `OAuthenticator.pre_spawn_start()` method, e.g. with `auth_state = yield user.get_auth_state()`. Does that not work?

**Comment by cyberquasar** [comment]
Didn't try that. I will give it a try.

**Comment by cyberquasar** [comment]
Thanks @davidbath @gsemet , finally, I was able to try the solution you suggested.

When I call `yield self.user.get_auth_state()` in `KubeSpawner._options_form_default(self):....` I get `traitlets.traitlets.TraitError: The 'options_form' trait of a KubeFormSpawner instance must be a unicode string, but a value of <generator object KubeFormSpawner._options_form_default at 0x7f5dc59e0ca8> <class 'generator'> was specified.` but when I do the same in ` def pre_spawn_start(self, user, spawner):..` it works smoothly.

@gsemet Will it be possible for you to share , what exactly you did to overcome this problem ?

**Comment by gsemet** [comment]
i do not remember having this issue. I don't think you can use yield in `_options_form_default`, these methods aren't asynchronous.

**Comment by consideRatio** [comment]
It is possible now to dynamically update the profile_list based on the user and its attributes, and then take individual action based on the choice before user is spawning.

Example: https://github.com/neurohackademy/nh2020-jupyterhub/blob/8bc0d8304d5090d3a1e21a038a68f0a940e31809/deployments/hub-neurohackademy-org/config/prod.yaml#L193-L269
