### ISSUE TITLE
event monitor causes infinite memory growth

### ISSUE THREAD

**Issue by minrk** [jupyterhub/kubespawner#165]
The event reflector in #150 has causes a memory leak, which brought down Binder last week.

I suspect we aren't properly cleaning up the reflector when we are done with it. We need to investigate and fix this before releasing kubespawner or pushing it to zero-to-jupyterhub.

**Comment by yuvipanda** [comment]
@minrk it isn't being used for anything right now, so I reverted it in #166

**Comment by minrk** [comment]
I [tracked it down](https://github.com/kubernetes-client/python-base/blob/789de6a60dea9442ee47601a788d92c653ea69e9/watch/watch.py#L65). Instantiating a Watch unconditionally instantiates an APIClient, which unconditionally spawns n_cpus threads. So when we create one reflector per pod, we are creating a *huge* number of threads.

It's the same as the kube-4.0 upgrade bug, but isolated to a more specific circumstance.

**Comment by minrk** [comment]
It does provide debug logging, and is used in #153. But I agree that we should probably revert it for now, or pin kubernetes-3 again.

**Comment by minrk** [comment]
I opened [a PR](https://github.com/swagger-api/swagger-codegen/pull/8061) with swagger-codegen, which is responsible for the flood of threads.

**Comment by yuvipanda** [comment]
@minrk let's just revert it, and introduce it back when needed. Does that sound right, @clkao?

**Comment by clkao** [comment]
Yeah please revert it for now, and I'll make this part of #153.  Is there any alternative way to make reflector sane before Watch() gets fixed by the swagger-codegen?

**Comment by minrk** [comment]
@clkao thanks. One way is to revert the kubernetes client to 3.x, which doesn't have this issue. We might also be able to find a workaround. I think we're not reliably cleaning these reflectors up, which could help.

**Comment by clkao** [comment]
hmm, i think the reflectors are stopped once the pod is running. maybe something is still missing.

**Comment by consideRatio** [comment]
> I tracked it down. Instantiating a Watch unconditionally instantiates an APIClient, which unconditionally spawns n_cpus threads. So when we create one reflector per pod, we are creating a huge number of threads.

The reflectors we use are now Singleton's - assuming this is resolved due to that.
