### ISSUE TITLE
Multiple deployments in the same namespace

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/kubespawner#173]
#### For reference
Kubespawner's `PodReflector` currently controls all pods within the same namespace by being hardcoded to find all pods within the namespace by using the label selection of `component=singleuser-server,heritage=jupyterhub`.

After [z2jh#625](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/625) and #161, this will be the only reason I know that holds the zero-to-kubernetes-k8s repo back from supporting multiple deployments within the same namespace. Something that I've come to understand can be useful on bare-metal clusters.

**Comment by ltalirz** [comment]
Given that the two mentioned PRs are merged, would it make sense to get rid of this last limitation?

**Comment by consideRatio** [comment]
Closing this as a duplicated of #76.
