### ISSUE TITLE
KubeSpawner._env_keep_default doesn't appear to serve a purpose.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jupyterhub/kubespawner#177]
Looking at this visually only, but can't see that ``KubeSpawner._env_keep_default`` would actually be used.

* https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L1254

It is not referenced anywhere in ``KubeSpawner`` code. The current JupyterHub ``Spawner`` base class doesn't define any similar attribute which it would be overriding. The base class just has:

```
    env_keep = List([
        'PATH',
        'PYTHONPATH',
        'CONDA_ROOT',
        'CONDA_DEFAULT_ENV',
        'VIRTUAL_ENV',
        'LANG',
        'LC_ALL',
    ],
        help="""
        Whitelist of environment variables for the single-user server to inherit from the JupyterHub process.
        This whitelist is used to ensure that sensitive information in the JupyterHub process's environment
        (such as `CONFIGPROXY_AUTH_TOKEN`) is not passed to the single-user server's process.
        """
    ).tag(config=True)
```

So the defaults are inline and not pulled from a separate attribute called ``_env_keep_default``.

This may be historical and maybe it did in the past.

Don't know if this would cause any issue or not, but suggests environment variables from JupyterHub process may be making there way into the notebook pod, possibly when not intended.

Comments?

**Comment by yuvipanda** [comment]
I *think* it can be taken out!

**Comment by consideRatio** [comment]
I'm not confident I got what you meant @GrahamDumpleton, but I looked at _env_keep_default recently as well and was confused it wasn't referenced anywhere, but then I learned that it is a magic function name with meaning to traitlets. In #236's commit https://github.com/jupyterhub/kubespawner/commit/5fcd4512e418ea43bc017c18d3b702456a4c3e57 I'm adding a decorator that will make it more obvious that the function has meaning even though it is not referenced.

**Comment by consideRatio** [comment]
It serves the meaning of resetting that list of env_keep to an empty list I think. It is poorly documented in the code, but I'll close this issue anyhow now.
