### ISSUE TITLE
[Kubeflow] KubeSpawner doesn't detect when pod is deleted

### ISSUE THREAD

**Issue by jlewi** [jupyterhub/kubespawner#178]
I seem to observe the following scenario in Kubeflow

1. Launch notebook
1. Notebook doesn't start; crash loops because of a problem inside the notebook container
1. Spawner doesn't detect this
1. Delete the notebook manually
1. Spawner still thinks the pod is being spawned

I'm using kube spawner 0.8.1

/cc @kkasravi @pdmack

**Comment by jlewi** [comment]
Restarting JupyterHub pod seems to fix it

**Comment by kkasravi** [comment]
[KubeSpawner 0.8.1](https://github.com/jupyterhub/kubespawner/blob/v0.8.1/kubespawner/spawner.py#L927) only checks if the pod is there. 
[KubeSpawner master](https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L1107) will check on the state of the notebook and the phase of the pod

Not sure when master will be released but it should fix this issue

**Comment by consideRatio** [comment]
Sounds like this is resolved, I think it is also!
