### ISSUE TITLE
Expose binder/notebook image name via environment variable to notebook container

### ISSUE THREAD

**Issue by jhamman** [jupyterhub/kubespawner#182]
*Note: this issue has a twin: https://github.com/jupyterhub/binderhub/issues/586*

I would like to find a way to expose the name (e.g. a GCR or dockerhub path) of the built docker image in the notebook environment. I want to do this because I'd like to give the name of this docker image to `dask-kubernetes` to support scaling computations done in a binder notebook across a larger kubernetes cluster.

I have looked at the current environment variables but it doesn't seem like this functionality is covered yet. 

(more discussion on the larger use case and progress related to this issue here: https://github.com/pangeo-data/pangeo/issues/283)

cc @betatim, @choldgraf, @katekinsman

**Comment by jhamman** [comment]
Just pinging this issue. Thoughts from the devs here would be appreciated.

**Comment by betatim** [comment]
I think this would be a useful feature to add. Maybe the lack of opposition means that the next step is for someone/you to open a PR that implements it. People tend to not comment too much if they are busy and not opposed :)

**Comment by jhamman** [comment]
Okay, thanks. I'm happy to submit a PR but would appreciate few tips on where you see this feature fitting. kubespawner is a new codebase for me so a few pointers would be appreciated.

**Comment by betatim** [comment]
The environment variables are set via a call to [`get_env()`](https://github.com/jupyterhub/kubespawner/blob/53b0ebd27893f5c6c914b130291fda674c6b5930/kubespawner/spawner.py#L1118). I'd define that method on the `KubeSpawner` class, call `get_env` from the base class, and then add to it the environment variable with the image name in it. I think the image name will be in `self.image_spec`.
