### ISSUE TITLE
progress events don't reset

### ISSUE THREAD

**Issue by minrk** [jupyterhub/kubespawner#184]
I've noticed that each time I launch a pod, I see all of the progress events from previous launches, not just those from the current launch. Somehow, the event list keeps growing rather than resetting on each call to start. It's unclear if this is in KubeSpawner itself, or if our request to events is getting past events for previous pods with our same name and we need to cut it off, either in the request (e.g. setting a time or generation cutoff), or truncating the list ourselves.

cc @clkao

**Comment by clkao** [comment]
yes, this is the expected current behaviour.  I meant to open a follow-up issue about this but it probably slipped.

The cause is that we use pod name for event field selector, rather than involvedObject.uid.

**Comment by minrk** [comment]
Thanks for the confirmation! This should be fixed by #186.
