### ISSUE TITLE
can't select images through jupyterhub admin console to  "add user->start server" to spawn single user server 

### ISSUE THREAD

**Issue by serlina** [jupyterhub/kubespawner#191]
Background, used kubespawner master. 2 settings in jupyterhub_config.py,
```
c.KubeSpawner.singleuser_image_spec = image_name1
```
2.

```python
c.KubeSpawner.profile_list = [
    {
        'display_name': 'server-small(1-256)',
        'default': True,
        'kubespawner_override': {
            'singleuser_image_spec': 'image_name2',
            'cpu_limit': 1,
            'mem_limit': '256M',
        },
    }, {
        'display_name': 'server-large(2-512)',
        'kubespawner_override': {
            'singleuser_image_spec': 'image_name3',
            'cpu_limit': 2,
            'mem_limit': '512M',
        }
    }
]
```

Test case1, if we don't set the configuration in 1 (c.KubeSpawner.singleuser_image_spec), it will raise error **"Failed to pull image "jupyterhub/singleuser:latest**" when we add user -> start server in jupyterhub admin console

Test case2, if we set both above configuration 1 and 2, when we add user -> start server in jupyterhub admin console, it will spawn a single user server using "image_name1" specified in configuration 1, and will not give us multiple image options specified in configuration 2.   

I think the behavior is not consistent, it is not correct. if we set the above configuration 2, the spawn process is  login jupyterhub -> start server -> select multiple image options -> spawn. So I think it should be consistent with this when we spawn server through jupyterhub admin console.

**Comment by minrk** [comment]
That's true! This is really a jupyterhub issue because the "start server" makes an API request to spawn, rather than sending you to the spawn form.

If you visit `/hub/spawn/username` you will get the spawn form for launching `username`'s server.

**Comment by lmerli84** [comment]
@minrk what about if I'm using KubeSpawner on top of WrapSpawner, both with a list of profiles. Do you believe it is possible to show both forms (before WrapSpawner one and then KubeSpawner one)? I'm getting only the WrapSpawner one.

Thanks
