### ISSUE TITLE
Support for Amazon EKS

### ISSUE THREAD

**Issue by jdavidheiser** [jupyterhub/kubespawner#194]
With the recent public launch of Amazon's Elastic Kubernetes Service, we've been interested in migrating over from our current Dockerspawner solution to Kubespawner on EKS, but without experience with either, are not sure how well supported EKS will be, as a new product.

Is there any information about what it would take to get Kubespawner working on EKS?  Any plan to add documentation on doing so?

**Comment by yuvipanda** [comment]
Thank you for opening this issue :) It's unclear to me how well baked EKS is right now too. However, more than 50% of kubernetes workloads seem to run on AWS, so Kubernetes support there is pretty good. Most people should use kops still, I believe.

I don't think there's anything specific needed for EKS support in KubeSpawner. There's active work on documenting this in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/299!
