### ISSUE TITLE
Bug: Exposing another port in the singleuser notebook

### ISSUE THREAD

**Issue by kalugny** [jupyterhub/kubespawner#195]
I want to have `RStudio Server` exposed on the singleuser container.
I've figured out how to use the proxy API to add the new route, but I still need the Pod to expose an additional port.

I've tried adding
```
c.KubeSpawner.extra_container_config = {'ports': [{'containerPort': 8787, 'name': 'rstudio-port', 'protocol': 'TCP'}]}
```
to the config, but it doesn't seem to work for some reason.
Setting a different config value (e.g. `{'bla': 'bla'}`) does crash the pod, so it is reading it, just ignoring the value for some reason....

Is there a way to do this using configuration?
Thanks!

**Comment by kalugny** [comment]
Sorry, wrong repo

**Comment by agt-ucsd** [comment]
@kalugny are you adding the new proxy route from within KubeSpawner?

**Comment by kalugny** [comment]
I actually gave up on adding the new proxy route, as this created a lot of complications.
I'm now using an NGINX proxy inside the `singleuser` image, which a much less "disruptive" solution.

The "bug" I found here is actually a bug in z2jh:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/745
so I'm closing here.
