### ISSUE TITLE
Documentation and Contribution

### ISSUE THREAD

**Issue by mogthesprog** [jupyterhub/kubespawner#2]
Hi,

I'm really interested in trying to get this working, and have no issue contributing code or Docs for this spawner.

If you could let me know how to get this working that would be great. :) I can then contribute back some docs at least, and fix any bugs i find.

Cheers,

Morgan

**Comment by yuvipanda** [comment]
Wonderful! Thank you for the offer! Do you have a kubernetes install you
can test this out on?

On Wed, Mar 9, 2016 at 5:06 AM, mogthesprog <notifications@github.com>
wrote:

> Hi,
>
> I'm really interested in trying to get this working, and have no issue
> contributing code or Docs for this spawner.
>
> If you could let me know how to get this working that would be great. :) I
> can then contribute back some docs at least, and fix any bugs i find.
>
> Cheers,
>
> Morgan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yuvipanda/jupyterhub-kubernetes-spawner/issues/2>.
>



-- 
Yuvi Panda T
http://yuvi.in/blog

**Comment by mogthesprog** [comment]
Sorry for the slow reply Uvipanda, I do have a kubernetes instance we could test this on :) I'll see how i get on and get back to you

**Comment by yuvipanda** [comment]
We have much better docs now - there's a SETUP.md in this repo for dev testing, and http://zero-to-jupyterhub-with-kubernetes.readthedocs.io/ for setting it up in production!
