### ISSUE TITLE
groups: cannot find name for group ID 2000

### ISSUE THREAD

**Issue by miramar-labs** [jupyterhub/kubespawner#204]
i'm running JupyterLab/kubespawner to launch the jupyter/all-spark-notebook as my user container/pod ... 

when I create a new Terminal window I get this:
groups: cannot find name for group ID 2000

also, if I type 'groups' I get the same message...

if I launch  jupyter/all-spark-notebook by itself, I don't get the message. Typing 'groups' returns 'users'

more info:
typing 'id' returns:
uid=1000(jovyan) gid=100(users) groups=100(users),2000

so i'm wondering what appended the 2000 there ...

**Comment by gweis** [comment]
Seeing the same issue here. My suspicion is, that kubernetes adds this somewhere via a default security context or so.
There were some release notes related to the runAsGroup property on SecurityContexts. I have not tried it yet, but trusting the release notes, this issue should go away with kubernetes 1.10.6+ and maybe setting the runAsGroup property on the SecurityContext.

**Comment by consideRatio** [comment]
Perhaps this is caused by uid/gid/fs_gid defaulting to 0, which I intend to fix in #453. I'll close this as stale and hopefully resolved by #453.
