### ISSUE TITLE
Starting pod for single-user notebook fails due to network not being granted.

### ISSUE THREAD

**Issue by cypherfox** [jupyterhub/kubespawner#207]
When I start a new singee-user instance, the start of the pods is stuck in initialization:

```Events:
  Type     Reason                  Age               From                                               Message
  ----     ------                  ----              ----                                               -------
  Normal   Scheduled               14s               default-scheduler                                  Successfully assigned jupyter-sage to gpu-node-1.icc.informatik.haw-hamburg.de
  Normal   SuccessfulMountVolume   14s               kubelet, gpu-node-1.icc.informatik.haw-hamburg.de  MountVolume.SetUp succeeded for volume "no-api-access-please"
  Normal   SuccessfulMountVolume   13s               kubelet, gpu-node-1.icc.informatik.haw-hamburg.de  MountVolume.SetUp succeeded for volume "pvc-d73d612f-7e83-11e8-b94a-0cc47afa35ea"
  Warning  FailedCreatePodSandBox  2s (x6 over 12s)  kubelet, gpu-node-1.icc.informatik.haw-hamburg.de  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "jupyter-sage_jupyterhub" network: connection is unauthorized
  Normal   SandboxChanged          1s (x6 over 11s)  kubelet, gpu-node-1.icc.informatik.haw-hamburg.de  Pod sandbox changed, it will be killed and re-created.
```

We are using a canal v3.1 (calico+flannel) as CNI plugin on a bare-metal cluster.
I have tried to create a pod manuall, using the specification generated by the kubespawner, removing elements of the security context of the nettools init container step by step.  Only if the security context is removed completely, the creation of the pod sandbox will succeed (obviously, then the call to iptables will fail do to missing permissions. This causes the whole pod to fail).

**Comment by consideRatio** [comment]
This is related to the Kubernetes cluster and more specifically the Container Network Interface (CNI) which often can vary and be configured. I'll close this as out of scope to debug for the kubespawner project.
