### ISSUE TITLE
Add support for specifying a hash of username in pod name / pvc templates

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/kubespawner#21]
Currently we support substituting `{userid}` with the id of the user in the jupyterhub database in pod names / PVCs. This is bad since losing the database now means we can't match users with their pods again, and more importantly we can not match them with their PVCs. This is what happened in https://github.com/data-8/infrastructure/blob/master/incidents/2017-02-09-datahub-db-outage.md.

We should strive to make the database not contain any irreplaceable information. Since the username is already provided to us by the authenticator, the userid is the only bit of information that doesn't exist outside the database. Just using username in pod names isn't good enough, since we have to restrict pod names to a subset of ASCII, which could cause clashes. Userid prevents these clashes, but causes problems when your db goes away.

So let's add support for `{USERNAMEHASH}` or somesuch, that allows us to add a hash of the username to the pod / PVC names. This should pretty much fix all our problems.

**Comment by minrk** [comment]
> Just using username in pod names isn't good enough, since we have to restrict pod names to a subset of ASCII, which could cause clashes.

You can always use ascii-safe escaped names, e.g. with [escapism](https://github.com/minrk/escapism). There's no way to have collisions there. DockerSpawner [does this](https://github.com/jupyterhub/dockerspawner/blob/0.6.0/dockerspawner/dockerspawner.py#L254).

**Comment by yuvipanda** [comment]
Using escapism now.
