### ISSUE TITLE
Special handling of reflector network errors

### ISSUE THREAD

**Issue by betatim** [jupyterhub/kubespawner#212]
https://github.com/jupyterhub/kubespawner/blob/fd2ff67a1a3e216a84f6e256cc8b77b225af63dc/kubespawner/reflector.py#L212-L214

Why is the network connection error handled specially instead of also backing off?

**Comment by gweis** [comment]
It is an expected event when setting `request_timeout` option on the reflector.

The default network timeout is 0, and will never trigger any timeout exceptions.  This option is there to force a reconnect to the api server, in case we have not received an event for `request_timeout` seconds. This is to avoid, waiting for events in case the underlying TCP connection has been interrupted, without the client socket knowing it. (e.g. iptables connection route got removed)

**Comment by consideRatio** [comment]
This is the current state of the same line of code.

https://github.com/jupyterhub/kubespawner/blob/f839b5ae215b35b779003952cb1ea1cd893ea32c/kubespawner/reflector.py#L258-L262

I hope @gweis answer helped, I'm not confident myself still but I want to close this issue at this point during my issue triage.
