### ISSUE TITLE
hub_connect_ip, hub_connect_port, hub_connect_url - ?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/kubespawner#224]
I ran into this warning while starting up a JupyterHub deployed with z2jh.

```
[W 2018-08-01 10:17:10.155 JupyterHub app:1129] JupyterHub.hub_connect_port is deprecated as of 0.9. Use JupyterHub.hub_connect_url to fully specify the URL for connecting to the Hub.
```

This is what it looks like in the z2jh hub's `jupyterhub_config.py`:

```python
c.JupyterHub.base_url = get_config('hub.base_url')
c.JupyterHub.db_url = get_config('hub.db_url')
c.JupyterHub.ip = os.environ['PROXY_PUBLIC_SERVICE_HOST']
c.JupyterHub.port = int(os.environ['PROXY_PUBLIC_SERVICE_PORT'])

# the hub should listen on all interfaces, so the proxy can access it
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.hub_connect_ip = os.environ['HUB_SERVICE_HOST']
c.JupyterHub.hub_connect_port = int(os.environ['HUB_SERVICE_PORT'])

# Spawner related
# ------------------------------------------------------------------------------
# Gives spawned containers access to the API of the hub
c.KubeSpawner.hub_connect_ip = os.environ['HUB_SERVICE_HOST']
c.KubeSpawner.hub_connect_port = int(os.environ['HUB_SERVICE_PORT'])
```

### KubeSpawner question
- Do we need to make a change within `kubespawner` as well?

### JupyterHub / Z2jh confirmation...
- Does this seem right?
```python
c.JupyterHub.hub_connect_url = '{host}:{port}'.format(
    host=os.environ['HUB_SERVICE_HOST'],
    port=os.environ['HUB_SERVICE_PORT']
)
```

**Comment by minrk** [comment]
> Do we need to make a change within kubespawner as well?

The kubespawner hub_connect logic should be deprecated, in favor of the JupyterHub config

JupyterHub 0.8 (or 0.7?) added `hub_connect` config itself, which had been implemented in a few different Spawners. The Spawner implementations should be slowly deprecated, instead relying on the hub config. The first step is to have the Spawner values default to the Hub config, with a warning when they are overridden directly.

**Comment by minrk** [comment]
>Does this seem right?

It should add `http://` at the beginning, but otherwise, yes.

**Comment by consideRatio** [comment]
@minrk ah thank you for the summary!

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/keyerror-proxy-public-service-host-in-k8s-hub-pod-logs/3638/2

**Comment by consideRatio** [comment]
We have updated the connection settings in jupyterhub_config.py part of the JupyterHub helm chart.
