### ISSUE TITLE
JupyterHub user deletion should imply PVC deletion

### ISSUE THREAD

**Issue by chang-zhijie** [jupyterhub/kubespawner#228]
Pvc can be created automatically, but it cannot be deleted automatically.

We can not delete the PVC even if we delete the user from jupyterhub. we need to manually delete  PVC. 

Can we add an option to delete pvc？

**Comment by johanfleury** [comment]
Just to add a bit more informations to this issue:

With `storage_pvc_ensure` set to `True` and `pvc_name_template` containing `{servername}`, a PVC will be created each time a user starts a new named server .

It would be great if KubeSpawner could remove the associated PVC when a named server is deleted (**not stopped**).

To avoid any data lost, I suggest that confirmation dialogs are displayed before sensitive actions, see jupyterhub/jupyterhub#2615.

**Comment by consideRatio** [comment]
I think spawners in general need a mechanism to cleanup resources, and have created https://github.com/jupyterhub/jupyterhub/issues/3197 to represent this wish.

**Comment by consideRatio** [comment]
Closing this in favor of #446
