### ISSUE TITLE
Add ability to handle imagePullSecrets for private docker registries

### ISSUE THREAD

**Issue by Analect** [jupyterhub/kubespawner#23]
@yuvipanda 
I was wondering if the kubespawner could be extended to handle a new parameter `imagePullSecrets`.

My use-case is that I'm using a private registry to contain images.  I'm running a cluster on GKE, which enables automatic authentication against the Google Cloud Registry (gcr.io), but not private ones.

As per these [docs](https://kubernetes.io/docs/user-guide/images/#configuring-nodes-to-authenticate-to-a-private-repository), there are a couple of work-arounds.  Specifically at the section `Creating a Secret with a Docker Config`, it shows how a secret for the private registry can be created.

Then, in order for an image contained in a kubernetes manifest file to get pulled (in our case, the image used to underpin a notebook server), then additionally the `imagePullSecrets` parameter needs to be supplied.

Here is an [example](https://gitlab.com/wolfhechel/kubernetes-deploy/commit/57c48b003511fcd1c34337b0f94817add5cd0703) of what I mean.

In the meantime, if I wanted to hard-code in a secret name, could I just add in that parameter [here](https://github.com/jupyterhub/kubespawner/blob/13edc761448f21b23f13d5b26b705b41c83b8c15/kubespawner/objects.py#L82)?

Thanks.

**Comment by yuvipanda** [comment]
Merged your patch now! Thank you very much!

**Comment by Analect** [comment]
@yuvipanda ... in case you didn't notice, just a heads-up .. the patch that @shraykay added [here](https://github.com/jupyterhub/kubespawner/pull/24) ended up not getting merged, since I think it was missing the new parameter in `test/test_objects.py` and failed in the build pipeline.
