### ISSUE TITLE
Can ReadWriteMany work in GCP?

### ISSUE THREAD

**Issue by PaulMazzuca** [jupyterhub/kubespawner#242]
Not sure if this is the appropriate venue for this question...  In the case where we would want users to share notebooks by sharing a mounted volume, does kubespawner in GCP support ReadWriteMany? If not, is there a way to allow multiple pods in GCP k8s to share a mounted volume that is writable?

**Comment by betatim** [comment]
Last time I checked there were no ReadWriteMany storage options on google managed kubernetes offering.

What people tend to do is setup a NFS instance and use that to have read/write many. There are a few issues around that in this repository as well as https://github.com/jupyterhub/zero-to-jupyterhub-k8s. Documenting the setup and operation of a NFS on k8s isn't something that is in scope for these projects.

**Comment by PaulMazzuca** [comment]
Thanks. I also found a blob describing how to setup NFS, though I have not yet tried it.  https://danielfrg.com/blog/2016/09/10/jupyterhub-kubernetes-nfs/
