### ISSUE TITLE
Pod is not deleted when was in ErrImagePull state

### ISSUE THREAD

**Issue by elgalu** [jupyterhub/kubespawner#250]
According to #22 a pod should be deleted if it's found in an errored state, however that's not the case for, for example, `ErrImagePull` state:

```
[Warning] Error: ErrImagePull
[Warning] Error: ImageInspectError
```

The hub never manages to delete this pod and the only workaround so far is to restart the Hub at which point the user is able to stop the pod and start his server again.

I wonder if this could be achieved without restarting the Hub.

**Comment by elgalu** [comment]
It's worth mentioning that the hub reports that it will kill the pod and recreate it:

```
2018-08-21 15:57:00+00:00 [Warning] Error: ErrImagePull
2018-08-21 15:58:00+00:00 [Normal] Pod sandbox changed, it will be killed and re-created.
Server requested
```

But it doesn't. It's stuck in that loop.

**Comment by elgalu** [comment]
I will need to correct myself a bit here. If I wait long enough the backoff and retry logic takes effect, and eventually it allows the user to start again. My problem was that I set a very long and exaggerated `start_timeout` of 35 mins because of my huge singleuser docker image.

What I would like to achieve is to only wait that long if the image is being pulled, but not in other cases like this one:

```
         "containerStatuses": [
            {
                "image": "testfail/image:latest",
                "imageID": "",
                "lastState": {},
                "name": "notebook",
                "ready": false,
                "restartCount": 0,
                "state": {
                    "waiting": {
                        "message": "Back-off pulling image \"testfail/image:latest\"",
                        "reason": "ImagePullBackOff"
                    }
                }
            }
        ],
        "hostIP": "172.31.11.98",
        "phase": "Pending",
        "podIP": "10.2.12.209",
```

**Comment by consideRatio** [comment]
I think JupyterHub / KubeSpawner now will delete pods that has failed to successfully respond to JupyterHub.
