### ISSUE TITLE
Make stop -> grace_seconds configurable

### ISSUE THREAD

**Issue by elgalu** [jupyterhub/kubespawner#254]
Right now `grace_seconds` for stopping a pod is either 0 or 1 second. I think is is quite a low number, the reason that is probably 30 seconds by default is because there should be enough time for a graceful container shutdown, if for example the singleuser containers run some services like a per-user Postgres or whatever.

Perhaps it would be valuable to have this configurable somehow.

https://github.com/jupyterhub/kubespawner/blob/5040e75022f302b3cbfadaa1ae18a5ab9d5563a0/kubespawner/spawner.py#L1760

**Comment by arturozv** [comment]
Yes please, I would like to export the conda environment in the preStop hook but the pod is killed before finishing

**Comment by consideRatio** [comment]
This makes sense to me - a PR is very welcome! Thanks @elgalu and @arturozv for reporting this!
