### ISSUE TITLE
Run c.KubeSpawner.lifecycle_hooks as root

### ISSUE THREAD

**Issue by PaulMazzuca** [jupyterhub/kubespawner#258]
Is there an easy way to run the lifecycle_hooks on the newly spawned pod as root?

The goal would be to add self-signed CA certs (that are mounted as volumes) to the notebook container after the container has been spawned.

**Comment by minrk** [comment]
I think this can't be done as a lifecycle hook, but it can be done with an `initContainer`. Would that work for you?

**Comment by PaulMazzuca** [comment]
I am not sure. I was under the impression that the initContainer ran another container within the Pod prior to the launch of the app container which would mean that file system that I would want root to affect would not even exist yet, because the app container has not launched.

**Comment by clkao** [comment]
If the filesystem is pvc, you can declare mounts in the initContainer and it will affect the notebook container's filesystem as they are shared.

**Comment by BerserkerTroll** [comment]
@PaulMazzuca `emptyDir` volume mounted into both the init and the app container should work.

**Comment by consideRatio** [comment]
I've seen @BerserkerTroll's approach work out fine, I would go this way I think.

**Comment by consideRatio** [comment]
The lifecycle_hook will run as the user the container is starting up as no matter what, so you can only control it like that. You can use an initContainer starting as root to avoid letting users be in a less restricted container environment.
