### ISSUE TITLE
Support kubespawner_merge on profile_list

### ISSUE THREAD

**Issue by elgalu** [jupyterhub/kubespawner#265]
https://github.com/jupyterhub/kubespawner/blob/5e35537db1091229c921830d78414a38de55740e/kubespawner/spawner.py#L1832

What do you think about having another option similar to `kubespawner_override` but named `kubespawner_merge` that instead of overwriting the property, it does a [dict merge](https://stackoverflow.com/a/20666342/511069) to just update or add what's needed.

**Comment by consideRatio** [comment]
@elgalu ah so the current functionality for `profile_list`, is to overriding some traitlet.

Hmmm... If we add merge for dicts, we would also want extend for Lists I figure. We could consider having `kubespawner_coalesce` and doing a `merge` for dicts traitlets, `extend` for list traitlets, and erroring on other options.

**Comment by consideRatio** [comment]
And now I need this =) I'm happy to make a PR implementing something like this, but it would be nice on guidance on what do implement.

## PR suggestion
1. Add a kubespawner_coalesce that would do do a shallow merge for dics and extend for lists
2. Throw warning if the same property is within kubespawner_override as well, but run the override parts first.

Makes sense?

**Comment by consideRatio** [comment]
I have considered this functionality quite a lot over time now, and I think it is too complicated feature to add to the KubeSpawner project. At the moment, I suggest the use of the various hooks that the spawners expose in order to do merges in the way that is wanted etc.
