### ISSUE TITLE
Events not showing up

### ISSUE THREAD

**Issue by akhilputhiry** [jupyterhub/kubespawner#272]
Earlier while using kubespawner it used to show events like image pulled successfully, container created, container started etc.. But now its showing only Server requested, Spawning server...

<img width="1547" alt="screen shot 2018-10-23 at 12 07 15 am" src="https://user-images.githubusercontent.com/747410/47311562-b4494680-d657-11e8-838e-f94cf6fed7e5.png">

**Comment by akhilputhiry** [comment]
@yuvipanda any thoughts

**Comment by yuvipanda** [comment]
Looks like the events are showing up, but the server isn't starting properly.

Can you look at the logs for the pod or for JupyterHub? That should give you a better idea for why your spawn is failing.

**Comment by akhilputhiry** [comment]
@yuvipanda I know why the spawn is failing.

My point is different, if you look at the event logs it is saying only 2 things

1. server requested
2. spawning server

Earlier it used to show that

1. pulling image from ..
2. image pulled successfully
2. creating container
3. started container

It used to show all the events we get while doing `kubectl desctibe pod <pod-name>`

```
Events:
  Type    Reason     Age   From                                      Message
  ----    ------     ----  ----                                      -------
  Normal  Scheduled  18s   default-scheduler                         Successfully assigned 2304677352/curl-5d895cfbc-dmrvd to acs-node22.usrno1.io
  Normal  Pulling    18s   kubelet, acs-node22.usrno1.asdaasdcloud.io  pulling image "docker.asdaasd.com/gbi-fw/curl:latest"
  Normal  Pulled     17s   kubelet, acs-node22.usrno1.asdaasdcloud.io  Successfully pulled image "docker.sdfsdf.com/gbi-fw/curl:latest"
  Normal  Created    17s   kubelet, acs-node22.usrno1.asdaasdcloud.io  Created container
  Normal  Started    17s   kubelet, acs-node22.usrno1.asdaasdcloud.io  Started container
```

**Comment by yuvipanda** [comment]
Ah, i see. I'm not sure - @minrk did most of the events work. Maybe he or @consideRatio have a better idea?

**Comment by consideRatio** [comment]
Thanks for the clear description and that you have taken time to report this behavior @akhilputhiry. Dont know whats going on, but i experienced an error like this during a quite quickly fixed development releasenof the zero-to-jupyterhub-k8s deployment of jupyterhub.

Are you using z2jh and if so, what version?

**Comment by consideRatio** [comment]
@yuvipanda!! :heart:

**Comment by akhilputhiry** [comment]
Hi @consideRatio I am not using z2jh for my deployment. I used kubeflow for my deployment.

**Comment by akhilputhiry** [comment]
@yuvipanda @consideRatio solved the problem

I was using [wrapspawner](https://github.com/jupyterhub/wrapspawner) to pick  up dynamic spawners. There they are not using child_classes progress method. I modified the wrapspawner to use child classes progress and it started working.

```
@async_generator
    async def progress(self):
        async for event in self.child_spawner.progress():
            await yield_(event)
```

**Comment by akhilputhiry** [comment]
I am trying to make kubespawner a generic framework to spin off any data science related stuff like
tensorboard, zeppelin etc.. I am able to spin off zeppelin notebooks and all.. working on making it compatiable with tensorboard and other stuffs.

**Comment by yuvipanda** [comment]
ah, cool. awesome :)

**Comment by TariniBindu03** [comment]
Hi for me Ian’s using Jupyter hub 5.1
![Uploading IMG_39DE0610-12C9-499A-A00C-EABF5BECA85F.jpeg…]()
 kubespawner 6.2 and Kubernetes 1.27 

pod is launching but events and redirection to lab not happening . Can you suggest me plz
