### ISSUE TITLE
kubespawner_overrides only read via the GUI, but not via the API

### ISSUE THREAD

**Issue by hhuuggoo** [jupyterhub/kubespawner#284]
I think this is a bug?

it looks like kubespawner_options is read and applied in options_from_form

https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L1816

However if named servers are spawned via the jupyterhub API

for example, this handler:

https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/apihandlers/users.py#L344

that option is passed and set on the spawner object as `user_options`

https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/user.py#L417

 but that isn't read by kubespawner?

If anyone can suggest how this should work?  (apply user options before spawning similar to in options_from_form before spawning?)

**Comment by yuvipanda** [comment]
/cc @minrk 

I'll try take a look tomorrow.

**Comment by rkdarst** [comment]
I noticed the same thing here, but promptly ran out of time before I could transfer here: https://github.com/jupyterhub/jupyterhub/issues/2126

Seems like kubespawner problem...

**Comment by hhuuggoo** [comment]
fwiw - I'm subclassing kubespawner currently, and doing this resolves the issue for me (so maybe something similar would be appropriate?  If so I'm happy to submit the PR

```
class KubeSpawner(_KubeSpawner):
    def start(self):
        options = self.user_options
        if options:
            kubespawner_override = options.get('kubespawner_override', {})
            for k, v in kubespawner_override.items():
                if callable(v):
                    v = v(self)
                    self.log.debug(
                        ".. overriding KubeSpawner value %s=%s (callable result)", k, v
                    )
                else:
                    self.log.debug(
                        ".. overriding KubeSpawner value %s=%s", k, v)
                setattr(self, k, v)
        return super().start()

```

**Comment by minrk** [comment]
Yeah, `user_options` is the 'real' options, which can be passed directly via the api. Everything should be really handled by looking at `self.user_options` in start. `options_from_form` ought to be strictly a transform from the restrictive html-form (everything's a list of strings) to a proper user_options dict, to be interpreted later.
