### ISSUE TITLE
Hub and Notebooks in different clusters

### ISSUE THREAD

**Issue by Spritekin** [jupyterhub/kubespawner#293]
Hi,

I have a question I hope someone can help me with.

For the last year, I have been running JupyterHub with a MesosCluster using DockerSwarm as the service manager on top of Mesos. The jupyterHub service runs in a separate cluster (AWS ECS) than the notebooks. When I need to spawn a notebook, JPHub asks dockerswarm and dockerswarm does all the work. Easy. 

Again, the cluster is only used to run the Notebooks. The JPHub service doesn't run in the cluster.

Due to DockerSwarm not being supported on Mesos, I need to change my cluster so I decided to use Kubernetes. My idea is still to use JupyterHub separate in ECS and when a user wants to start a notebook, the command is sent to Kubernetes.

I have been reading the Kubespawner but unfortunately I can't find the parameter where I point JPHub to the Kubernetes cluster I want to use to run the notebooks. Can someone please tell me if this setup is possible?

Regards,
Guimo

**Comment by consideRatio** [comment]
Tank you for describing this use case @Spritekin ! It is not currently supported by kubespawner.

We are utilizing the python library called "kubernetes" which is like a python API for `kubectl`. We would have to wrap a way to configure this library to utilize credentials to access another cluster etc.

Helm would not be able to provide the credentials for that cluster, so we would need to rely on manual permissions to be configured ahead of time as well, and some service account setup ahead of time.

It seems quite complicated to support this, while probably possible. If you find an idea on how to go about it I'd be interested in it!

**Comment by manics** [comment]
There's this try-catch where the config is loaded:
https://github.com/jupyterhub/kubespawner/blob/4b3e1c1a5f9e0f4c360c5acda9f75edb6e58aa2d/kubespawner/reflector.py#L129-L132

Looks like if Kubespawner is run outside a cluster it should use your current kube-config?

**Comment by Spritekin** [comment]
Thank you for your responses.
Yes I went through all the code and found it essentially uses the PythonAPI. So I think if we can write a kube config file we should be abler to do this.

What we are doing is writing an entrypoint.sh script that pyggybacks the standard jupyterhub startup and writes a kube config on the fly when the container is started. That way when the API calls attempts loading the configuration, the file should be there already.

Will test this and report back.

Regards,

**Comment by totycro** [comment]
@Spritekin I'm about to try something very similar to what you are describing. Did you have any luck with this approach?

**Comment by consideRatio** [comment]
Hi all!

As I don't see any concrete action point to take with regards to the content of this git repository, I'm closing this to indicate its a no-action kind of issue.
