### ISSUE TITLE
Access to docker/runtime options (PID limits)

### ISSUE THREAD

**Issue by vilhelmen** [jupyterhub/kubespawner#303]
I've been triaging some stability issues with our kubernetes cluster (short version, [don't use centos7](https://github.com/moby/moby/issues/37722) and/or [recompile containerd ](https://github.com/opencontainers/runc/pull/1921), or you'll eventually run out of kernel memory and the host will start locking up). After experimenting, I found that a fork bomb triggers the issue quickly. While the kernel memory leak can be fixed/mitigated, I'm now worried about DoS via PID exhaustion, accidental or not.

Docker seems to have PID limits via the run flag `--pids-limit`. Is it possible to access other docker commandline options like this through the spawner API? 

I appreciate the help! I wouldn't be surprised if the low level argument control is firewalled from the API.

Perhaps pid limits can be enforced inside the container via ulimit, but I'm not sure since that seems like something that would involve the kernel.

**Comment by manics** [comment]
Kubespawner supports configuration for additional resource limits: https://github.com/jupyterhub/kubespawner/blob/v0.9.0b2/kubespawner/spawner.py#L988
It looks like Kubernetes may have support for limiting PIDs: https://github.com/kubernetes/kubernetes/pull/57973, that's for an old version so it might no longer be alpha, you'll need to check

**Comment by vilhelmen** [comment]
That's a good catch! Looks like it was added in 1.10. I'll have to see what I can do, I'll report back.

Is there an easier way to see what commit in in a release other than searching the release commit history? I've never found a better way and this way is hell.

**Comment by vilhelmen** [comment]
Well I've managed to reconfigure the cluster somehow, but there's zero docs on how to set the flag through the API (there's an issue ticket for it lol). I'm just assuming it's configured in a similar fashion to those configured adjacent in the code.

I tried to jam it in `extra_pod_config` as `podPidsLimit`, but I got a V1 validation error. It just might be that since it's not part of the V1PodSpec, it's not letting it through, maybe if I comment validation it out... Any potential sage advice is appreciated while I poke around.

**Comment by celine168** [comment]
Have you had any luck with this? I didn't have luck with setting ulimits and I'm not sure how to set extra resource limits in the config file.

**Comment by vilhelmen** [comment]
Thanks for the reminder! I got absolutely nowhere trying to fight kubespawner to accept my config. I didn't really want to mod the spawner to try and make it accept it. I'm very bad at k8s.

But, more importantly, I have a **BIG WARNING** for anyone that tries to go the ulimit route: You will super duper mess up jupyter sessions and probably need to set it to like 500+

I tried setting it to 200 and student sessions would eventually grind to a halt. The process limit counts threads and the jupyter worker threads add up incredibly quickly. Jupyter doesn't fail gracefully when it can't spawn threads, buttons just stop doing things.

**Comment by celine168** [comment]
Thank you for responding! I'll have to keep those limits in mind. It sounds like the PID limits affected the `hub-xxx` pod somehow? 

I'm trying to mitigate fork bombs too and was thinking of modifying some kind of Kubernetes config directly but a blanket PID limit on all of the pods in a cluster seems like a bad idea now...

**Comment by vilhelmen** [comment]
The limit was restricted to the user's container, but some students managed to open enough notebooks to hit the 200 limit; each open notebook eats up at least 5+ processes/threads. At that point, parts of the session stopped working and nothing would happen when the user tried to open more notebooks/terminals.

Now that you mention it, putting the pid limit into k8s would most likely have the same results. You just have to set the limit surprisingly high. Maybe around 500-1000 would work well in general?

**Comment by celine168** [comment]
I see, I'll try to test it out on a test JupyterHub. Could I please ask how you changed the ulimits? I think I tried setting them in a Dockerfile, which led to an error. I also tried setting them inside JupyterLab's terminal but it didn't seem to stop a fork bomb.

**Comment by vilhelmen** [comment]
I make heavy use of the before-notebook.d system. You just need to dump scripts into `/usr/local/bin/before-notebook.d/` and make sure your container starts as root to trigger the scripting/setup system.

You may also need to set the singleuser command to `/usr/local/bin/start-notebook.sh`, but I set `singleuser.cmd` to `null` in our z2jh configuration and that works. I recall having issues getting the right script to start and that fixed it, but I'm not sure if it's still necessary.

I keep a bunch of [slightly sanitized example stuff over here](https://github.com/vilhelmen/jh-k8-etc/tree/master/singleuser-shim/before-notebook.d) if you want to poke around, but I haven't updated it in awhile.

Here's our current ulimit script, tweak to your heart's content. When a memory limit is in effect we apply a VMEM limit because we've found that R's allocator tends to respect memory limits, which means R will usually return an error message instead of crashing. I'm not sure how python handles it, we don't tend to have memory issues with python. I'm suspicious of virtual memory limits, so be careful with it if you go with it.

```bash
#!/bin/bash
# 25-apply-ulimits.sh

# kubespawner is putting {MEM,CPU}_{LIMIT,GUARANTEE} in the env
# >:C ulimit wants KB why. I mean, I get that allcoating like 30 bytes is not useful, but still.
if [ ! -z ${MEM_LIMIT+x} ]; then
	#ulimit -m $(expr ${MEM_LIMIT} / 1024)
	# Ugh, physical limits aren't being respected. VMEM limits seem to, though.
	# But virtual memory is virtual, so it shouldn't be the problem???
	ulimit -v $(python3 -c "print(int(${MEM_LIMIT} / 1024 * 0.95))")

	# I'm setting the process limit to like 200 because I want to try and stop forkbombs
	# If you REALLY need more than 200 processes when you have 2 cores... my dude...
	# ulimit -u 200
	# Also only enforce only when memory is enforced (read: disable process limits when you're unconstrained)
	# LOL OK THIS MIGHT BE A COUNTER AND ALL THE INTERNAL THREADS DING AGAINST THIS
fi
```

**Comment by consideRatio** [comment]
Kubernetes Kubelet, which runs on each k8s node, can be started with `--pod-max-pids` it seems, but that is not something that KubeSpawner can configure as part of registering a Pod with the k8s api-server. I'll go ahead and close this issue as unresolvable as part of this project.
