### ISSUE TITLE
matrix of profile_list options

### ISSUE THREAD

**Issue by rabernat** [jupyterhub/kubespawner#307]
I would like to give users an option to select _independently_ between machine options (e.g. `cpu_limit`) and notebook image.

I imagine that this may be possible already, either through some `profile_form_template` magic or by supplying a callable as profile_list. But I thought I would ask for suggestions here before diving too deep into either of these. Perhaps the devs already have a good idea about the easiest way to accomplish this.

**Comment by consideRatio** [comment]
Ah so like a set of independent choices that would then be merged together?

- Current situation: we are using N sets of predefined options.
- Your Matrix suggestion  as I understand it: is having sets of sets of options that then is merged.
- Related to this: allowing for multiple choice for individual options within an item within a profile_list set of options.

**Comment by rabernat** [comment]
Yes exactly.

Symbolically, I would specify the profile list like something like this
```python
{'memory_options': [
    {
        'display_name': 'Low Memory',
        'kubespawner_override': {
            'mem_limit': '512M',
        }
    }, {
        'display_name': 'High Memory',
        'kubespawner_override': {
            'mem_limit': '2G',
        }
    } ]
 'image_options' [
    {
        'display_name': 'Image A',
        'kubespawner_override': {
            'image': 'training/datascience:A',
        }
    }, {
        'display_name': 'Image B',
        'kubespawner_override': {
            'image': 'training/datascience:B',
        }
    } ]
}
```

I would like to see two different multiple-choice areas on the spawner form: one for `memory_options`, one for `image_options`.

**Comment by rabernat** [comment]
If someone can give me some advice about how to get started, I could consider starting a PR to implement this. I think we would want to discuss and agree on the needed data structures first.

**Comment by keniseli** [comment]
I'd love to help with the implementation. Is the desired outcome already clear enough?

**Comment by rabernat** [comment]
Hi @consideRatio -- @keniseli is a new contributor to Pangeo and we identified this issue as a good place to start.

It would be great if you or some of the other devs could give him some pointers on how to get started.

**Comment by consideRatio** [comment]
Thanks for the ping @rabernat and welcome @keniseli! I think you are asking the perfect question right away =)

Some steps that I think makes sense to take initially:
- Clarify a proposals impact for the end user experience
- Clarify a proposals way to configure Kubespawner
- Try get a local development environment up and running according to the docs here, or perhaps the docs in jupyterhub/zero-to-jupyterhub-k8s that has modern docs on setting up at k8s cluster with some tools that was not around when this docs were written.

The big question I have regarding this feature regards how how well it can generalize. I'd like to avoid situations where we add support for A and B because we feel they are relevant, but end up asked for C D E F etc later. I hope that we find a balance.

**Comment by rabernat** [comment]
> * Clarify a proposals impact for the end user experience

I'll do my best to give my input on this part. Currently, the end user experience is to select a single profile list choice from a multiple-choice menu. These options combine many (possibly unrelated) categories, including  `image`, `cpu_limit`, `mem_limit`, and `extra_resource_guarantees` (e.g. GPU).

Under this proposal, it should be possible to configure a hub for a different user experience. Instead of a single multiple-choice list, there could be several distinct multiple choice lists, e.g. `image`, `cpu_limit`, etc. The user would choose one option from each list, and the resulting union of options would determine the set of options that are passed to Kubespawner.

> * Clarify a proposals way to configure Kubespawner

While I have a clear vision for the end-user experience, I don't know the best way to configure Kubespawner to accomplish this. Here I would welcome the advice of the devs.

**Comment by consideRatio** [comment]
Something like...
- Support allowing end users to choose a value from a dropdown box for a given configuration option.
- (not clear yet) should profile_list provide a list of predefined options as before, and let each option contain options to choose specific values etc?

Hmmm... Another way of saying it perhaps is to say that we want the user to be allowed to choose from a set of profiles, but for the profile chosen also specify additional details.

**Comment by consideRatio** [comment]
@jcrist have done a nice similar feature for dask-gateway, where the admins can expose options for users as described here: https://gateway.dask.org/cluster-options.html.

There may be some issues with regarding reusing that code base though as I think we may require this to run on JupyterHub's webserver as compared to being inside a Jupyter server. I'm not knowledgeable about these details though.

**Comment by jcrist** [comment]
There's also https://github.com/ResearchComputing/jupyterhub-options-spawner, which may be of use here.

**Comment by rabernat** [comment]
Wow, options-spawner looks amazing! Perhaps we can accomplish what we need with that, without any changes to KubeSpawner.

**Comment by keniseli** [comment]
I'll take a closer look into it. Thanks for the information so far!

**Comment by kyprifog** [comment]
@keniseli  were you able to confirm that jupyterhub-options-spawner in conjunction with kubespawner would allow you to have profile specific limits?

**Comment by keniseli** [comment]
@kyprifog  unfortunately, I wasn't able to dig into it yet. I will have the chance to look into it until end of Sept latest.

**Comment by yuvipanda** [comment]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/30430/165632127-426a08f3-420a-4489-9a46-2a298ad3482e.png">

here's a prototype!

**Comment by yuvipanda** [comment]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/30430/166382052-a3e004fd-8a88-415c-9964-c0005c755c70.png">

Better :D
