### ISSUE TITLE
how to invoke the test scripts to verify kubespawner

### ISSUE THREAD

**Issue by srams2018** [jupyterhub/kubespawner#308]
Hi,
i checked the below link and not sure how to invoke the test spawn class. is it the travis.yaml that invokes this? any directions will be helpful.
https://github.com/jupyterhub/kubespawner/tree/1e858e85cd722d47e856ae8c2e64eb7099e71c6f/tests

**Comment by consideRatio** [comment]
At the moment, the related documentation available is those found in [SETUP.md](https://github.com/jupyterhub/kubespawner/blob/master/SETUP.md). It would be great to get feedback if this works for you @srams2018 ! It was a while since I used them last.

**Comment by srams2018** [comment]
Thanks for the steps @consideRatio. let me give a try
