### ISSUE TITLE
Named server pod name typo

### ISSUE THREAD

**Issue by vilhelmen** [jupyterhub/kubespawner#323]
Looks like there's a small hiccup in the named server pod name generation that always appends 2d to the name of the server. Maybe in KubeSpawner._expand_user_properties ? I'm not very familiar with the variables involved, but is appears that 0x2d is '-', so something is getting misinterpreted somewhere.

Tested with master Z2JH using JH 1.0.1 and kubespawner 0.10.1

<img width="399" alt="image" src="https://user-images.githubusercontent.com/5308250/58054135-43034080-7b1f-11e9-9ba3-2298114a25ff.png">

**Comment by dmarth** [comment]
This is a known issue (#300). The fix has already been merged into the master branch (#309).

**Comment by betatim** [comment]
Thanks for noting the duplicate. Closing.
