### ISSUE TITLE
username for the form "aaa-bbb" gets PVC like: "claim-aaa-e2bbb-XXXX"

### ISSUE THREAD

**Issue by gsemet** [jupyterhub/kubespawner#324]
I suggest to keep the "-" character like this. 

I can make a PR if accepted.

**Comment by consideRatio** [comment]
I've struggled to come to terms with this also, but the crux is that the `-` character is used to escape other characters and we have very few available for k8s naming. Whatever follows a `-` character is meant to encode an actual character when we escape the user provided parts of the PVC name.

If we provide hell@oworld.com and hello@world.com and simply strip out the characters that needed escaping instead, like `@` and `.`, then both of these provided names would end up as helloworldcom, so escaping has a purpose. An option would be to force the user of kubespawner to be restrictive themselves or delegate the escaping to them.

I think, if we should change something in kubespawner, it would be to make this escaping configurable and default to what it currently is.

If the escaping is turned off, a check should also be made, throwing an error if it is passed something that cannot be written out as a k8s resource name. I guess the escaping configurable option could allow you to say how to treat that as well, like "oh please throw an error if i try to provide a name that needed escaping" or "oh please just strip unusable symbols" or "oh please just replace unusable symbols with `-`"`.

I'm not confident about this matter to say that a PR of something like this would be sensible enough to add, where the key concern then would be that if anything is added it needs to be considered for all the future time.

**Comment by gsemet** [comment]
my mistake, it is a dot : usernames come from our Gitlab OAuth2 in the form "name.lastname". I update the issue title.

I agree this is not really needed, it is just the name of the pvc that has a `-2e` instead of a dot. I can actually fix is early one

**Comment by consideRatio** [comment]
Can a PVC have a . in its name though? If it is a k8s resource that you can use `kubectl get ...` on, then ... (looking it up)...

> By convention, the names of Kubernetes resources should be up to maximum length of 253 characters and consist of lower case alphanumeric characters, -, and ., but certain resources have more specific restrictions.

https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

Ah okay `.` is allowed along with `-` and the alphanumeric characters.

**Comment by consideRatio** [comment]
Oh... But if the dots are escaped, but doesn't need to be escaped, that is a different thing I guess. I assumed that the character needed escaping.

**Comment by gsemet** [comment]
I have set this in my extraConfig and so my PVC replace "." by "-" while still escaping everything else:
```python

    # Prevent replacement of "." by "-2e" in the username in PVC
    from kubespawner import KubeSpawner
    import string
    import escapism
    class ReescapedKubeSpawner(KubeSpawner):
      def _expand_user_properties(self, template):
          # Make sure username and servername match the restrictions for DNS labels
          # Note: '-' is not in safe_chars, as it is being used as escape character
          safe_chars = set(string.ascii_lowercase + string.digits)
          safe_chars.add(".")

          # Set servername based on whether named-server initialised
          if self.name:
              servername = '-{}'.format(self.name)
              safe_servername = '-{}'.format(escapism.escape(self.name.lower(),
                                                             safe=safe_chars, escape_char='-').replace(".", "-"))
          else:
              servername = ''
              safe_servername = ''

          legacy_escaped_username = ''.join([s if s in safe_chars else '-' for s in self.user.name.lower()])
          safe_username = escapism.escape(self.user.name.lower(), safe=safe_chars, escape_char='-').replace(".", "-")
          return template.format(
              userid=self.user.id,
              username=safe_username,
              unescaped_username=self.user.name,
              legacy_escape_username=legacy_escaped_username,
              servername=safe_servername,
              unescaped_servername=servername
          )

    c.JupyterHub.spawner_class = ReescapedKubeSpawner
```

My PVC looks great: check_circle `claim-firstname-lastname`. 

Now I only see how i can "fix" the pod name: `jupyter-firstname-2elastname`

**Comment by gsemet** [comment]
Ok something I can spen hours on a simple stuff...

More direct solution;
```yaml
singleuser:
  storage:
    dynamic:
      pvcNameTemplate: 'jhub-claim-{legacy_escape_username}{servername}'
      volumeNameTemplate: 'jhub-volume-{legacy_escape_username}{servername}'
```
This fixes the pvc and the volume name.

Now the pod name...

**Comment by gsemet** [comment]
Ok, I had to hack again in the `extraConfig`
```python
c.KubeSpawner.pod_name_template = "jupyter-{legacy_escape_username}{servername}"
```
Would be cool if the `_expand_user_properties` function can accept another item, for example the app release name for example (still in the goal of multiple jhub in the same namespace)

**Comment by consideRatio** [comment]
@gsemet sure PR sounds good for being able to configure the pod_name_template, I'm a bit sad that we dont have a passthrough to configure all kubespawner stuff in a single config section though. But that is another issue.

Btw, spotted what perhaps may be a typo that I don't understand fully, and it is regarding writing the left hand side differently from the right hand side:
>              legacy_escape_username=legacy_escaped_username,

Will need to return to this issue to consider it further with a clear mind, I'm currently having a lot of headache. Hmmm... Thinking out loud off topic... is there is some plugin to chrome or something to help me get back to this issue in some time?

**Comment by consideRatio** [comment]
I think we are forced to escape usernames `-` characters to avoid security issues. `-` acts as the separation between named servers, and if a username can be created with `-` in it without getting it escaped, it could make it seem like it will own a named servers PVC for example.
