### ISSUE TITLE
z2jh's single.extra-env does not seem to be consummed

### ISSUE THREAD

**Issue by gsemet** [jupyterhub/kubespawner#325]
On my z2jh install with multiple profiles, it seems like ``singleuser.extraEnv`` config is not transfered to the pod.
The configuration file ``singleuser.extra-env` is well written in the hub's `/etc/jupyter/config`, but my users do not have the variables set on their pods.

Using z2jh 0.7.0.

**Comment by gsemet** [comment]
It only works if I inject the environment variable in `extraConfig` with `c.KubeSpawner.environment = ...`

**Comment by consideRatio** [comment]
I don't think this is an issue with current z2jh, but i remember there were some keys that were ignored before. Closed assumed to be resolved, but we should of course reopen this if it can be reproduced either in kubespawner itself, or opened in z2jh if this isn't working there.

**Comment by kyprifog** [comment]
@consideRatio I just tried to use extraEnv in response to this comment:  https://github.com/dask/helm-chart/issues/131 and it doesn't appear to be working.   The only caveat is that I'm also using profileList and spinning up the image in profileList and I haven't figured out if that requires a different syntax.
