### ISSUE TITLE
Spawning users without attaching PVC storage

### ISSUE THREAD

**Issue by afeiszli** [jupyterhub/kubespawner#326]
Perhaps there is a specified way of doing this but I couldn't find it in the documentation.

Issue: I would like to remove all volumes and volume mounts for single user pods. To do so I have overridden the jupyterhub_config.py file with the following:

```
c.KubeSpawner.volume_mounts = []
c.KubeSpawner.volumes = []
```

However, when attempting to spawn a pod, the KubeSpawner still creates storage, and also returns this error, due to volumeMount[0] no longer being defined.:

```
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"my-little-notebook-nb-feiszli-2dalex-2dc\" is invalid: spec.containers[1].volumeMounts[0].name: Not found: \"data\"","reason":"Invalid","details":{"name":"my-little-notebook-nb-feiszli-2dalex-2dc","kind":"Pod","causes":[{"reason":"FieldValueNotFound","message":"Not found: \"data\"","field":"spec.containers[1].volumeMounts[0].name"}]},"code":422}
```

**Comment by consideRatio** [comment]
Hmmmm. I see no trace of KubeSpawner injecting volumes by default. It seems like you end up with a volumeMounts referencing a volume named data.
