### ISSUE TITLE
Configuring terminationGracePeriodSeconds to help preStop from getting killed.

### ISSUE THREAD

**Issue by madsi1m** [jupyterhub/kubespawner#330]
Hi i am using preStop setting to run a script before killing the container/pod. I've noticed that this script does not complete.

I have set  start_timeout = 3000 (which also sets the stop timeout) and have set

```python
c.KubeSpawner.extra_pod_config = {
        'terminationGracePeriodSeconds': 3000
    }
```

When i query the pod i can see that the Grace period is set correctly.

So it seems that something else is sending a KILL to the pod, at around the 10s mark.

Any ideas what this might be? Is there something i am missing?

**Comment by consideRatio** [comment]
Hmmm, I think this is overridden, as when KubeSpawner is stopping the pod it does so by declaring its patience explicitly.

https://github.com/jupyterhub/kubespawner/blob/c02c61c457e498192fdf9f240c2bcaec373f9f95/kubespawner/spawner.py#L1770-L1776

**Comment by madsi1m** [comment]
possible to tag as a version?

**Comment by consideRatio** [comment]
https://github.com/jupyterhub/kubespawner/blob/c02c61c457e498192fdf9f240c2bcaec373f9f95/kubespawner/spawner.py#L1110-L1120

**Comment by madsi1m** [comment]
I worked out the issue. Latest from github let’s me use delete grace period. But the latest release doesn’t. Is it possible to release the current master as a version so I can import it via setup tools in my projects?

**Comment by yinhua-dai** [comment]
I also have the problem.
Even latest jupyterhub-0.9.0-alpha.1.104.d37322a doesn't use the grace period.

When can we have a chart which uses kubespawner 0.11.*?

**Comment by consideRatio** [comment]
Please provide the configuration you attempted to use to se the grace period from the z2jh config.yaml @yinhua-dai.

**Comment by madsi1m** [comment]
something like this
```
c.Spawner.delete_grace_period = 3600 # +600
    c.Spawner.extra_pod_config = {
        'terminationGracePeriodSeconds': 3000
    }
```

**Comment by consideRatio** [comment]
Make it c.KubeSpawner and try again. The generic base class Spawner does not know of such configuration, only KubeSpawner does

**Comment by consideRatio** [comment]
This issue is a bit too complicated to follow at this point for me. I'm closing this as too unconcrete for this project to take action on.

Because I'm a bit curious, I looked up some details.

> This hook is called immediately before a container is terminated due to an API request or management event such as liveness probe failure, preemption, resource contention and others. A call to the preStop hook fails if the container is already in terminated or completed state. __It is blocking, meaning it is synchronous, so it must complete before the signal to stop the container can be sent.__ No parameters are passed to the handler.

Further, start_timeout (which is also stop_timeout, see #253), is just how long JupyterHub is to patiently wait, it does not influence k8s patience receiving a pod deletion request for the preStop hook to finish, which I think is infleunced by terminationGracePeriodSeconds.
