### ISSUE TITLE
kubernetes version limit

### ISSUE THREAD

**Issue by jmabry** [jupyterhub/kubespawner#332]
The setup.py file specifies kubernetes client version `'kubernetes>=7.0'` but there is a backwards-compatibility breaking change in the kubernetes client for version 10.0.0a1 as noted in https://github.com/kubernetes-client/python/issues/808.

Specifically, the imports in https://github.com/jupyterhub/kubespawner/blob/3bec1ba6802de97095835fd393ed7fc53bf2cca2/kubespawner/objects.py#L449 will now throw an error.

**Comment by minrk** [comment]
Looks like this was only an issue in the alpha, and fixed in 10.0 stable. The kubespawner tests pass with kubernetes 10.0.0.
