### ISSUE TITLE
It is valid to have storage_class be an empty string.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jupyterhub/kubespawner#335]
In `make_pvc` the code uses:

```
    if storage_class:
        pvc.metadata.annotations.update({"volume.beta.kubernetes.io/storage-class": storage_class})
        pvc.spec.storage_class_name = storage_class
```

This is incorrect as it is valid to be able to specify a storage class name which is an empty string. Quoting the docs:

> PVCs don’t necessarily have to request a class. A PVC with its storageClassName set equal to "" is always interpreted to be requesting a PV with no class, so it can only be bound to PVs with no class (no annotation or one set equal to ""). A PVC with no storageClassName is not quite the same and is treated differently by the cluster depending on whether the DefaultStorageClass admission plugin is turned on.

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1

The code should thus read:

```
    if storage_class is not None:
        pvc.metadata.annotations.update({"volume.beta.kubernetes.io/storage-class": storage_class})
        pvc.spec.storage_class_name = storage_class
```

where default value for `storage_class` is `None`.

This is notification of issue. PR will likely be coming.

**Comment by minrk** [comment]
closed by #337
