### ISSUE TITLE
Add configuration on runtime

### ISSUE THREAD

**Issue by 223311** [jupyterhub/kubespawner#341]
For one of the requirement , I came across this package and trying to install. Just wanted to know whether we can able set **configuration** of  an pod on the fly.
for an example 
  when I spawn on image, it should ask for  **RAM**  or storage etc.
Is there any possible to create one pod with given resources from user  and spin up that pod.

thank you in advance for any and all feedback

**Comment by kevin-bates** [comment]
Does the `profile_list` stuff address this? https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L1032-L1098

I believe that hooks into the spawner 'options form': https://jupyterhub.readthedocs.io/en/latest/reference/spawners.html#spawner-options-form

**Comment by 223311** [comment]
Thanks:)
