### ISSUE TITLE
expand_all used where maybe it should not be

### ISSUE THREAD

**Issue by rokroskar** [jupyterhub/kubespawner#345]
The [`_expand_all`](https://github.com/jupyterhub/kubespawner/blob/8a6d66e04768565c0fc56c790a5fc42bfee634ec/kubespawner/spawner.py#L1268) method is used to sanitize various properties to meet the k8s API requirements and fill in useful runtime values like usernames. However, it's not needed to be used everywhere and it can cause unwanted side-effects - for example, in https://github.com/jupyterhub/kubespawner/blob/8a6d66e04768565c0fc56c790a5fc42bfee634ec/kubespawner/spawner.py#L1334-L1335 it's used to escape the annotation and label values, but these do not need to be DNS safe and if modified they mean that clients expecting a specific annotation or label will not find what they are looking for. Furthermore, the limitations of these key/value pairs are slightly different - in the case of labels, they are limited to alphanumeric characters with `.`, `/`, `-`, and `_` *and* must be less than 64 characters. For annotations, the length limitation only applies to the keys but not the values. See syntax and character set descriptions for [annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set) and [labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/).

IMO the method `_expand_user_properties` that does the template replacement and string cleanup should either be split in two or not applied to all fields.

**Comment by betatim** [comment]
Want to make a PR with a solution?

**Comment by rokroskar** [comment]
sure, be happy to - I opened this issue to throw the question out there - maybe there is a good reason why it's implemented this way and I don't want to break existing functionality that others are relying on.

**Comment by consideRatio** [comment]
Related to #316, but a separate issue.

I'm not sure what to suggest with regards to escaping conditionally with regards to where the escaping is needed or not. I have noted though that there is an option to use `{unescaped_username}` for example, which means that you can avoid the escaping of the expanded field by using the `unescaped_` version.

https://github.com/jupyterhub/kubespawner/blob/3dfe870a7f5e98e2e398b01996ca6b8eff4bb1d0/kubespawner/spawner.py#L1339-L1346

I assume this is the fix to the issue for now and close it.
