### ISSUE TITLE
Failed to connect to Hub API (strange JUPYTERHUB_API_URL)

### ISSUE THREAD

**Issue by djangoliv** [jupyterhub/kubespawner#348]
Error: Failed to connect to Hub API at 'http://jupyterhub-test-994bb7878-mzrvz:8080/hub/api'.  Is the Hub accessible at this URL (from host: my-user-pod)?

The kubernetes yaml look strange for JUPYTERHUB_API_URL and JUPYTERHUB_ACTIVITY_URL. The pod can't ping http://jupyterhub-test-994bb7878-mzrvz.
I would like to change these vars with something like 
JUPYTERHUB_API_URL = https://jupyterhub.intra.foo.fr

Especially if my jupyterhub pod dies, I want the user's pods to continue to live

```
>> kubectl get pod my-user-pod -o yaml
...
spec:
  containers:
  - env:
  ...
    - name: JUPYTERHUB_API_URL
      value: http://jupyterhub-test-994bb7878-mzrvz:8080/hub/api
    - name: JUPYTERHUB_ACTIVITY_URL
      value: http://jupyterhub-test-994bb7878-mzrvz:8080/hub/api/users/ogiorgis/activity
...
```

My conf:

```
# notebooks
notebook_dir = '/home/jovyan/'

# spawner
c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'
c.KubeSpawner.debug = True
c.KubeSpawner.default_url = '/lab'
c.KubeSpawner.mem_limit = '4G'
c.KubeSpawner.notebook_dir = notebook_dir
c.KubeSpawner.image = 'my-image'
c.KubeSpawner.start_timeout = 60 * 5  # Up to 5 minutes
c.KubeSpawner.namespace = 'my-namespace'
...
c.JupyterHub.log_level = 'DEBUG'
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.ip = '0.0.0.0'
#c.JupyterHub.hub_connect_url = 'https://jupyterhub.intra.foo.fr' # tried with this without succes

```

Regards

**Comment by crauterb** [comment]
I am currently observing the same error message.
Have you tried/had any success trying to define the `api_url` using specific values in the config or using the env. variable `JUPYTERHUB_API_URL` ?

**Comment by djangoliv** [comment]
I tried the both option without success. I ended up modifying the source code of spawner.py
      ```diff
   env['JUPYTERHUB_USER'] = self.user.name
         env['JUPYTERHUB_SERVER_NAME'] = self.name
-        env['JUPYTERHUB_API_URL'] = self.hub.api_url
+       env['JUPYTERHUB_API_URL'] = os.environ['JUPYTERLAB_API']
         env['JUPYTERHUB_ACTIVITY_URL'] = url_path_join(
-           self.hub.api_url,
+          os.environ['JUPYTERLAB_API'],
            'users',
            # tolerate mocks defining only user.name
            getattr(self.user, 'escaped_name', self.user.name),
```

**Comment by consideRatio** [comment]
I fail to translate this issue into something concrete to change with regards to this project. I also lack a bit much information to understand the situation.

JUPYTERHUB_API_URL is [set by the Spawner base class part of JupyterHub](https://github.com/jupyterhub/jupyterhub/blob/27e83a32605cf7a39a7af8240128469e36b57402/jupyterhub/spawner.py#L764). And, as documented in https://github.com/jupyterhub/kubespawner/issues/359#issuecomment-687159369, `c.KubeSpawner.environment` will be able to override `JUPYTERHUB_API_URL` if you wish to use something other than the default which is set by JupyterHub to be the same as `c.JupyterHub.api_url` I think.

**Comment by djangoliv** [comment]
The possibility to override JUPYTERHUB_API_URL makes the job. 

Thanks a lot.
