### ISSUE TITLE
Adding NodeAffinity, Nodeselector, Toleration in JupyterHub Helm chart version 0.7.0

### ISSUE THREAD

**Issue by ramkrishnan8994** [jupyterhub/kubespawner#350]
I can't see a proper documentation to add **NodeAffinity, Nodeselector, Toleration** in the Helm Chart v0.7.0. I read that **c.KubeSpawner.singleuser_extra_pod_config** is deprecated. 

I can see the same in v0.8.2 chart but we have a dependency issue stopping us from using this version.

@consideRatio @yuvipanda

**Comment by consideRatio** [comment]
Closed in favor of: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1402
