### ISSUE TITLE
extra_pod_config does not allow overriding specific values in nested dicts

### ISSUE THREAD

**Issue by aberey** [jupyterhub/kubespawner#352]
I want to add the `securityContext.allow_privilege_escalation` field, but defining `securityContext` in `extra_pod_config` will replace the complete `securityContext` dict. This also means fields like `runAsUser` (that are defined in `securityContext` through the `uid` config) get lost. What's more, I cannot define such dynamic fields in the overriding `securityContext` config, since `extra_pod_config` does not resolve callables.

It would be useful to have a merging functionality for nested dict values similar to what https://github.com/jupyterhub/kubespawner/issues/265 suggests for the profile_list config. At the very least, it would help to make the `extra_pod_config` a Union() type instead of Dict() that allows using a callable, or resolve lambdas embedded into the dict similar to how the `environment` config is implemented.

**Comment by consideRatio** [comment]
Closed by #450 which was merged some hours ago. It will be part of the next release, we are now at 0.14.1, so it will be 0.14.2 or 0.15.0.
