### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/kubespawner#364]
I'd like to make a release and bump to use it within z2jh. I'm trying to bring up many dependencies to z2jh so I don't have time to focus 100% on any individual repository though =/

On limited time, I've looked through the PRs in kubespawner. I'd like to put attention on these.
- [x] About scoping security matters properly, either on Pod/Container level - https://github.com/jupyterhub/kubespawner/pull/334
- [x] About locating storage with a selector - https://github.com/jupyterhub/kubespawner/pull/338
- [x] About k8s 1.16 - https://github.com/jupyterhub/kubespawner/pull/362

**Comment by bitnik** [comment]
@consideRatio I think you can close this issue :)
