### ISSUE TITLE
Ingress rules w/o host wont match

### ISSUE THREAD

**Issue by remche** [jupyterhub/kubespawner#404]
### Bug description
Ingress rules for singleuser pods wont match if a rule with host field for hub server exists : 

```
NAME                                                      HOSTS                ADDRESS   PORTS   AGE
jupyter--2fuser-2fgpu-2f-route                            *                              80      42m
jupyterhub                                                gpu-hub.host.tld                80      46m
```

#### Workaround
Manually adding the host to the ingress fixes the mismatch. 

#### Expected behaviour
The proxy implementation should add the host field to the ingress rule, or at least optionally allow it.

### How to reproduce
I did test with Traefik and nginx-ingress controller.
Note that kubernetes-ingress (NGINXinc implementation) does not even support a rule with no host  : nginxinc/kubernetes-ingress#209.

### Your personal set up
- K8s v1.15.11 (RKE)
- nginx-0.25.1-rancher1 or Traefik 2.0.6

**Comment by remche** [comment]
I'm not sure because not an expert of JH architecture but I think using `bind_url` or `base_url` is not a solution.

What about adding an optional proxy parameters to specify the host for the ingresses objects ?

**Comment by dolfinus** [comment]
There are 2 ways to implement that:
1. Add a bunch of options for Ingress customization, like #406 or #648. This can solve the issue, but users can ask for adding a lot of options, like custom annotations, path suffixes and so on.
2. Add analog for `modify_pod_hook`, but for ingress (and maybe service and endpoints) created by `kubespawner.objects.make_ingress`. Users can customize whatever they want with just a little support
