### ISSUE TITLE
How do I get username when doing an API call via Kubespawner?

### ISSUE THREAD

**Issue by averageflamethrowerguy** [jupyterhub/kubespawner#412]
Hey folks, I'm trying to do an API call using the jupyterhub username to an API to populate profileList. However, it looks like os.getenv('JUPYTERHUB_USER') returns None. 

```python
import os
jhub_user = os.getenv('JUPYTERHUB_USER')
URL = "https://api.example.com/api/user/payplan/" + jhub_user
r = requests.get(url = URL)
```

Is there a variable in Kubespawner that I can use to get the unique username, or is there another unique identifier that I can use?
Thanks!

**Comment by chicocvenancio** [comment]
Not sure where you're using this, but KubeSpawner.user should have the user model.

**Comment by averageflamethrowerguy** [comment]
Yes, I apologize, I'm using this in the extraConfig section of the config.yaml file.

**Comment by averageflamethrowerguy** [comment]
What I ended up doing was turn this into a callable. I'm currently trying to specify a custom postStartHook. As far as I can tell, the syntax should be 
`[
{'display_name': '<name of display>',
 'slug': 'qbraid',
  'default': True, 
  'image': 'image-url', 
  'cpu_guarantee': 1, 
  'cpu_limit': 8, 
  'mem_guarantee': '2G', 
  'mem_limit': '32G', 
  'lifecycle_hooks': 
        {'postStart': 
             {'exec': 
                   {'command':  ['/bin/sh', '-c', 'command-to-execute']
}}}}
]`
[
{'display_name': '<name of display>',
 'slug': 'qbraid',
  'default': True, 
  'image': 'image-url', 
  'cpu_guarantee': 1, 
  'cpu_limit': 8, 
  'mem_guarantee': '2G', 
  'mem_limit': '32G', 
  'lifecycle_hooks': 
        {'postStart': 
             {'exec': 
                   {'command':  ['/bin/sh', '-c', 'command-to-execute']
}}}}
]
but that doesn't seem to be working.

Here's my solution for the dynamic profileList (the API route returns a profileList) in case anyone else runs into this while googling.

`import requests
      import json
      import copy
      from tornado import gen

      @gen.coroutine
      def get_profile_list(spawner):
          auth_state = yield spawner.user.get_auth_state()
          if spawner.user.name:
            api_url = "https://api.example.com/api/spawner-profiles/" + spawner.user.name
            data_json = requests.get(url = api_url, verify=False).json()
            data_json_str = str(data_json)
            data_json_str = data_json_str.replace("'", '"')
            data_json_str = data_json_str.replace("True", "true")
            data_python = json.loads(data_json_str)
            return(data_python)

      c.KubeSpawner.profile_list = get_profile_list`

**Comment by utkarshyadavin** [comment]
@averageflamethrowerguy I am facing the same problem. I am trying to get the user name from the spawner using spawner.user.name in the pre_spawn_hook function but I don't think it is returning any value. 

hub:
  db:
    type: sqlite-pvc
    pvc:
      storageClassName: gp2
  extraConfig:
    spawner: |
      def new_hook(spawner):
        username = spawner.user.name
        if(username == 'user123'):
          c.KubeSpawner.events_enabled = False
      c.KubeSpawner.pre_spawn_hook = new_hook

I don't see anything being returned in username here. Can you help?

**Comment by averageflamethrowerguy** [comment]
I'm not sure, as its been a little while since I cracked this, but try:
`extraConfig:
     spawner: |
             @gen.coroutine
              def new_hook(spawner)
                     .  .  .
                  return hook

     c.KubeSpawner.events_enabled = False
     c.KubeSpawner.pre_spawn_hook = new_hook`

Basically, I'd suggest returning the hook from the coroutine and then overriding the default hook outside the coroutine.

**Comment by consideRatio** [comment]
I think either https://github.com/jupyterhub/kubespawner/pull/393#issuecomment-703309234 or [this configuration example may be helpful](https://github.com/neurohackademy/nh2020-jupyterhub/blob/da35049a93d372fe501b7968687e703a5e048e30/deployments/hub-neurohackademy-org/config/prod.yaml#L213-L289) as examples.

Note that it felt impossible to answer the original question without getting information on where the code snippet was running. Was it in the hub pod, or in a user server pod etc - in other words, where was the API call you wanted to make supposed to be made from.
