### ISSUE TITLE
Add ability to override component label 'singleuser-server'

### ISSUE THREAD

**Issue by harsimranmaan** [jupyterhub/kubespawner#413]
### Proposed change
The current component label is hard coded and does not allow for need based customization.
Add an option to kubespawner to allow setting `component` label to a value other than 'singleuser-server'.

### Who would use this feature?

Would be really helpful in running multiple Jupyterhub instances in the same namespace.

### (Optional): Suggest a solution

Add a config option called `component-label` that defaults to 'singleuser-server' but can be set to another value if needed. Maybe add some validation on what values are accepted like format and length.

Happy to send a PR.

**Comment by consideRatio** [comment]
Closed by #418
