### ISSUE TITLE
High CPU usage in the reflector

### ISSUE THREAD

**Issue by rmoe** [jupyterhub/kubespawner#423]
The Python Kubernetes client by default deserializes API responses into objects. This takes a lot of time when you're processing events for thousands of pods. During a test run where we created 2000 users and servers the hub process spent a large percentage of its CPU time just deserializing these responses. Here's a flamegraph from [py-spy](https://github.com/benfred/py-spy) that was captured during the entire scale test:

![image](https://user-images.githubusercontent.com/26524/90191483-d1dc2880-dd75-11ea-9125-94f3c59d10ab.png)
During that run 54% of the hub's CPU time was in `_watch_and_update` and within that method it was dominated by calls to the api deserialization methods.

If the reflector deals in JSON instead the graph from an identical run looks like this:
![image](https://user-images.githubusercontent.com/26524/90264268-af91eb80-de05-11ea-810b-212f231cc995.png)

(Github won't let me upload the SVGs py-spy generates but I can provide those another way if anybody wants to drill into them).

During these scale tests the wall time between the runs doesn't actually vary that much. However the reduced CPU load makes the hub API much more respsonsive. With the default kubespawner when scaling from 1000 to 2000 (and beyond) new servers take progressively longer to spawn and the API becomes unresponsive. Those runs are littered with errors like:

```
2020-08-13 14:38:13,454 WARNING [urllib3.connectionpool] Retrying (Retry(total=9, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='host', port=443): Read timed out. (read timeout=30)")': /hub/api/users/hub-stress-test-1361/server
```
Those errors go away when we don't deserialize the responses.

### Proposed change
The watcher can pass `_preload_content=False` to the method in `list_method_name` which will return JSON from the API. The reflector can just keep that data as dictionaries instead of deserialized objects. 

### Who would use this feature?

Everybody

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/identifying-jupyterhub-api-performance-bottleneck/1289/6

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/core-component-resilience-reliability/5433/6

**Comment by consideRatio** [comment]
I just want to say thank you @rmoe for a fantastic report of the situation! :heart: This certainly motivates an improvement!

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/core-component-resilience-reliability/5433/8
