### ISSUE TITLE
Kubespawner has naming collisions when multiple jupyterhub deployments are running in the same namespace

### ISSUE THREAD

**Issue by kristofmartens** [jupyterhub/kubespawner#434]
### Proposed change
The kube spawner naming templates only support userid, username, and servername. When deploying multiple jupyterhubs in the same namespace (yes this is smth we would like to do), this will cause naming conflicts if the same user will log in to different hubs on different deployments. This manifests itself as: Disks from other deployments being mounted, pods from other deployments being killed as they see one already running with the expected name (from a different deployment)

### Alternative options
Reuse the servername parameter for that (self.name)

### Who would use this feature?
People and companies running multiple jupyterhub instances in the same namespace

### (Optional): Suggest a solution
Solution to this problem would be to make these spawned pods release dependent by allowing release name as a name template variable as well.

**Comment by kristofmartens** [comment]
#431 is the proposed PR to address this issue

**Comment by manics** [comment]
Resolved by https://github.com/jupyterhub/kubespawner/pull/418
