### ISSUE TITLE
Move to native async functions for coroutines

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/kubespawner#435]
# Proposed change

Right now, we use tornado's `@gen.coroutine` along with `yield` statements for our coroutines. Since JupyterHub is now Python 3.5+, we can switch to using Python native `async/await` syntax. This should be a fairly mechanical and straightforward switch - tornado has been running on asyncio for a while now.

### Alternative options

Keep `gen.coroutine`. This is tornado specific though, so would be good to deprecate.

### Who would use this feature?

All developers who interact with the codebase.

### (Optional): Suggest a solution

We make a big PR making this purely syntactical change, and merge it in such a way that it causes minimal rebasing issues for other open PRs

**Comment by manics** [comment]
Sounds good to me! I find the current mix of async/await with `tornado.gen` confusing

**Comment by yuvipanda** [comment]
This looks done!
