### ISSUE TITLE
Deleting named servers should delete the corresponding PVC

### ISSUE THREAD

**Issue by PMende** [jupyterhub/kubespawner#446]
## Current state

In the current implementation of z2jh on k8s, when a named server is started, a PVC is created, which is what we want to happen. When a user *stops* their server, this PVC persists, which we also want to happen. Currently, when a user *deletes* their named server, the corresponding PVC is not deleted or released.

Persisting the PVC after the deletion of the servers leaves stranded claims that have to be manually cleaned up. Additionally, if a user creates an identically-named server sometime later, their seemingly newly created server will be attached to this stranded claim since the k8s resource names will point at each other. Thus a "newly" created server will not be a clean environment.

## Proposed change

The PVC for a named server should be deleted when the named server is deleted.

**Comment by manics** [comment]
Can we move this to jupyterhub-idle-culler instead? There's discussion of expanding its role:
- https://github.com/jupyterhub/jupyterhub-idle-culler/issues/8
- https://github.com/jupyterhub/jupyterhub-idle-culler/issues/9
Potentially it could also clean up "orphaned" volumes and other resources. As a standalone service this faster to develop than a new Spawner/JupyterHub API.

**Comment by consideRatio** [comment]
@manics hmmm, then the Culler would need to become k8s aware it sounds like to me. If the jupyterhub-idle-culler currently is generic to JupyterHub, I think this issue should stay in KubeSpawner.

Thank you for connecting these related issues together @manics! The question in my mind is not to flesh out a viable implementation path to resolving the issues. With the path I suggest, this belongs in KubeSpawner, but if we would embed k8s logic in jupyterhub-idle-culler, then it would belong there I think.

**Comment by manics** [comment]
The idea of those linked issues is to look at ways of extending the culler, for instance with plugins. It would then be fine to have k8s specific methods in a plugin.

**Comment by nsshah1288** [comment]
Hi @consideRatio @manics 
I am also looking into this issue.

I see in spawner.py this code: https://github.com/jupyterhub/kubespawner/blob/40fa25a60a2640515fdd5eb8503f85580596eec6/kubespawner/spawner.py#L1970 , which makes an API request to delete the pod.

If I wanted to implement this, would I need to add a new method in spawner.py that calls the DELETE persistent volume API request? And then how to call this method from JupyterHub?

Am new to this code so any advice would be great :) Thanks!

**Comment by nsshah1288** [comment]
Hi @manics @consideRatio @minrk 
I have gotten this to work, that when you delete a user from the admin console, it deletes the corresponding PVC and user's storage.
I have only so far tested locally using sqlite-pvc, but I am going to test as well with EFS in a few weeks.

If there is interest in this change, I would be happy to submit a PR, just let me know. Thanks

**Comment by octavd** [comment]
Hello,

It would be amazing to have that feature implemented in kubespawner. Is there any chance this will be implemented?
@nsshah1288 could you please detalil how you actually implemented this?

**Comment by nsshah1288** [comment]
hi @octavd ! Check out these two PRs:
https://github.com/jupyterhub/jupyterhub/pull/3337
https://github.com/jupyterhub/kubespawner/pull/475/files

and this thread: https://github.com/jupyterhub/jupyterhub/issues/3197

Unfortunately, I was not able to figure out a test case for kubespawner PR so that one is not approved yet, but the `delete_forever` method in spawner.py worked for me to delete the PVC.

**Comment by octavd** [comment]
Hey @nsshah1288 , so i was able to run your modified jupyterhub + kubespawner in an openshift 4 env.
Using the hub admin after clicking on remove user it removed also his PVC. Tried also with the JupyterHub api and it's ok.

Is there any way to speed up this feature to be added in the official branch? It would be very nice that these features available.

**Comment by nsshah1288** [comment]
Hi @octavd , great that it works for you!
I will try and see if I can figure out the test case, also if you have any idea on how to write the test be my guest :)

**Comment by nsshah1288** [comment]
Hi @manics @consideRatio could you please review the PR here: https://github.com/jupyterhub/kubespawner/pull/475 ?
I recently fixed the test case. Thanks!
