### ISSUE TITLE
Release 0.17.0, 17.0.0, or 1.0.0?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/kubespawner#505]
@jupyterhub/jupyterhubteam I'd like to cut a release for KubeSpawner for Z2JH to make use of soon.

I'd also in general like to start working with major.minor.patch versions and not just 0.minor.patch as there is far less flexibility to communicate what kind of changes to expect when one only has an ability to bump two version specifiers.

### Question
Due to this, I wonder if you think it's okay if we cut a major release, and, if we do, use 17.0.0 or 1.0.0.

### Current state
We are currently on 0.16.1 and the changes since then are the following: https://github.com/jupyterhub/kubespawner/pulls?q=is%3Apr+merged%3A%3E%3D2021-03-01. These include a breaking change in the sense that PVCs will now be deleted as part of deleting a user or removing a named server.

**Comment by minrk** [comment]
Happy for 17.0 for me

**Comment by choldgraf** [comment]
I feel similarly here as to how I feel on Z2JH - just start at 1.0, and in the changelog make an explicit note that 1.0 is the "continuation of 0.16" and that we are now switching to a more traditional semver approach (so breaking changes are major version changes), and that pre-1.0, _minor_ version changes should be considered breaking changes.

**Comment by yuvipanda** [comment]
+1 to choldgraf - the Java 1.x to x changes confuse me still...

**Comment by consideRatio** [comment]
Thanks for your input! Based on this and previous question in z2jh, I'll prepare a changelog and such for 1.0.0 rather than 0.17.0 or 17.0.0.
