### ISSUE TITLE
{username} does not expand for service_account

### ISSUE THREAD

**Issue by reganmcdonald** [jupyterhub/kubespawner#512]
Bug description
I am attempting to dynamically assign services accounts to singleuser pods based on the username.

Expected behaviour
c.KubeSpawner.service_account('user-{username}') results in c.KubeSpawner.service_account('user-myusername')

Actual behaviour
serviceaccount "user-{username}" not found"

**Comment by consideRatio** [comment]
I think this is a very reasonable feature request. Anyone wanting to make a PR go for it!

## Action points
- [ ] Add a test to see if a service account name is expanded by the make_pod function that returns a k8s Pod manifest.
- [ ] Make the make_pod function expand the configured service account name.
- [ ] Document that the service account configuration will also expand things like username as it does for environment variables.

**Comment by reganmcdonald** [comment]
Thanks @consideRatio. In the meantime I am trying to use a prespawn hook to accomplish this, but not able to get it to work yet. This is what I have:

`singleuser:
   extraConfig:
     pre-spawn-hook: |
       def my_pre_spawn_hook(spawner):
           username = spawner.user.name
           spawner.service_account = "user-" + username

       c.KubeSpawner.pre_spawn_hook = my_pre_spawn_hook`

Is the above correct?
