### ISSUE TITLE
pod security context supplementalGroups [] instead of None since 1.0.0 , conflict with PSPs

### ISSUE THREAD

**Issue by chrisbulgaria** [jupyterhub/kubespawner#513]
### Bug description
psc["supplementalGroups"] gets a default value of [] instead of None since this change :
https://github.com/jupyterhub/kubespawner/pull/480/files.
This conflicts with clusters having pod security policies, see here for more background:
https://discourse.jupyter.org/t/singleuser-pod-fails-after-1-0-0-upgrade-on-supplementarygroups-with-psp/9660

#### Expected behaviour
previous behaviour, supplementalGroups=None

### How to reproduce
Deploy z2jh 1.0.0 to cluster with psp's enabled.

### Your personal set up
z2jh 1.0.0 , no relevant entries in values.yaml
# paste relevant logs here, if any
```
Error on deployment:
spec.securityContext.supplementalGroups: Invalid value: []int64{}: unable to validate empty groups against required range 

In log , deployment descriptor:
'security_context': {'fsGroup': 100, 'supplementalGroups': []},

( a workaround is to set c.KubeSpawner.supplemental_gids explicitly to eg [100])

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/singleuser-pod-fails-after-1-0-0-upgrade-on-supplementarygroups-with-psp/9660/1

**Comment by consideRatio** [comment]
https://github.com/jupyterhub/kubespawner/blob/98bb5773f0d1c8e0c065c7259511ea38103eabe9/kubespawner/objects.py#L401-L416

The logic is wrong here.

```diff
- if supplemental_gids is not None: 
+ if supplemental_gids: 
     psc["supplementalGroups"] = [int(gid) for gid in supplemental_gids] 
- if pod_security_context is not None: 
+ if pod_security_context: 
```
