### ISSUE TITLE
c.KubeSpawner.default_url doesn’t work

### ISSUE THREAD

**Issue by EtgarSH** [jupyterhub/kubespawner#531]
### Bug description

When I change the `c.KubeSpawner.default_url` attribute in `jupyterhub_config.py` file to `/lab`, nothing changes.

#### Expected behaviour

The Jupyterlab homepage to be shown instead of Jupyter Notebook.
#### Actual behaviour

Jupyter Notebook is shown.

### How to reproduce

1. Change the attribute to `/lab`.
2. Launch the server for the user.
3. `/tree` is still shown instead of `/lab`.

**Comment by manics** [comment]
Could you show us your full JupyterHub config with secrets redacted, versions of all components, and show us your Dockerfiles?

**Comment by consideRatio** [comment]
I bet this is a duplicate of https://github.com/jupyterhub/kubespawner/issues/493#issue-826161387 in practice.

**Comment by consideRatio** [comment]
> 2\. I think the logic to silently ignore the traitlets `args`, `notebook_dir`, `default_url` when `cmd` is unset is problematic and should lead to a warning at least.

I assume `cmd` is no longer set to `jupyterhub-singleuser`.

**Comment by EtgarSH** [comment]
> I bet this is a duplicate of [#493 (comment)](https://github.com/jupyterhub/kubespawner/issues/493#issue-826161387) in practice.
> 
> > 2. I think the logic to silently ignore the traitlets `args`, `notebook_dir`, `default_url` when `cmd` is unset is problematic and should lead to a warning at least.
> 
> I assume `cmd` is no longer set to `jupyterhub-singleuser`.

Do you have any idea of a workaround solution to deal with this issue?
