### ISSUE TITLE
Kubespawner does not set CPU_LIMIT when setting kubespawner_override.extra_resource_limits.cpu

### ISSUE THREAD

**Issue by stefanmeisner** [jupyterhub/kubespawner#548]
### Bug description
When overriding resource limits and guarantees environment variables are not overwritten

#### Expected behaviour
When configuring a profile with kubespawner_override like:
      kubespawner_override:
        extra_resource_limits:
          cpu: 16

I would expect CPU_LIMIT=16 in environment

This is taken from kubectl describe pod:

    Port:          8888/TCP
    Host Port:     0/TCP
    Args:
      jupyterhub-singleuser
      --ip=0.0.0.0
      --port=8888
      --SingleUserNotebookApp.default_url=/lab
      --debug
    State:          Running
      Started:      Mon, 22 Nov 2021 13:38:40 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     16
      memory:  32G
    Requests:
      cpu:     500m
      memory:  6G
    Environment:
      JUPYTERHUB_API_TOKEN:           329b3574462c4667b0161c729d7d5034
      JPY_API_TOKEN:                  329b3574462c4667b0161c729d7d5034
      JUPYTERHUB_ADMIN_ACCESS:        1
      JUPYTERHUB_CLIENT_ID:           jupyterhub-user-steml
      JUPYTERHUB_HOST:                
      JUPYTERHUB_OAUTH_CALLBACK_URL:  /aw-development/user/steml/oauth_callback
      JUPYTERHUB_USER:                steml
      JUPYTERHUB_SERVER_NAME:         
      JUPYTERHUB_API_URL:             http://hub:8081/aw-development/hub/api
      JUPYTERHUB_ACTIVITY_URL:        http://hub:8081/aw-development/hub/api/users/steml/activity
      JUPYTERHUB_BASE_URL:            /aw-development/
      JUPYTERHUB_SERVICE_PREFIX:      /aw-development/user/steml/
      MEM_LIMIT:                      4294967296
      MEM_GUARANTEE:                  2147483648
      CPU_LIMIT:                      2.0
      CPU_GUARANTEE:                  0.5

#### Actual behaviour
CPU_LIMIT matches the value of singleuser.cpu.limit

### Your personal set up
zero-to-jupyterhub, helm chart 1.2.0 on AKS
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by consideRatio** [comment]
The environment variables are set to be generally helpful for CPU/Memory, but not the extra resources. Extra resources should be things that isn't CPU/Memory related. For things cpu/memory related, use these configuration options.

Note that KubeSpawner is based on the JupyterHub Spawner class, which is aware about CPU/Memory, but isn't k8s aware, so this configuration is stemming from a non-k8s-aware context, which makes these resources be configured in a k8s unintuitive way.

![image](https://user-images.githubusercontent.com/3837114/142890521-26cee66a-5ba4-4740-9f6d-7d9c64afb04c.png)

An example use of extra_resource_limits would be `{ "nvidia.com/gpu": 1 }` for example, where you set a limit of 1 GPU. For anything you want to do with regards to cpu/memory, don't use `extra_resource_limits`.

**Comment by stefanmeisner** [comment]
Setting cpu and memory in the profile is very useful for us. What other options do we have for choosing cpu/memory resources "on the fly"?

**Comment by consideRatio** [comment]
You can do:

```
kubespawner_override:
  cpu_limit: ...
  cpu_guarantee: ...
  memory_limit: ...
  memory_guarantee: ...
```
