### ISSUE TITLE
Doesn't seem to work with non-ascii usernames

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/kubespawner#55]
If I use DummyAuthenticator and try to log in with 经济 as username it fails.

**Comment by yuvipanda** [comment]
Works fine with SimpleLocalProcessSpawner, so it must be something in kubespawner.

**Comment by consideRatio** [comment]
I think this is resolved by escaping usernames and such, since it hasn't been updated and such for a very long time I'll close it as probably resolved.
