### ISSUE TITLE
Allow specifying traitlet config for the singleuser

### ISSUE THREAD

**Issue by holdenk** [jupyterhub/kubespawner#553]
### Proposed change
Allow specifying traitlet config for the singleuser

### Alternative options

Write a shell script generate the config

### Who would use this feature?
People who want to configure off the beaten path traitlets that don't support being configured through the command line well.

**Comment by consideRatio** [comment]
> Allow specifying traitlet config for the singleuser

The JupyterHub Helm chart has singleuser.extraFiles, it will create a k8s Secret resource to contain the text/yaml/json you pass into the k8s Secret, then mount it to a file in the user pod by updating KubeSpawners volumes/volumeMounts.

See https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#singleuser-extrafiles

I don't think we should make kubespawner do this itself at this point. JupyterHub Helm chart users -> singleuser.extraFiles, kubespawner users -> creation of k8s Secret/ConfigMap's -> define kubespawner volume / volume_mounts.
