### ISSUE TITLE
jupyterhub not understanding pod network

### ISSUE THREAD

**Issue by csbrown** [jupyterhub/kubespawner#57]
There's probably a config setting for this...
I have a real network on 10.0.0.0/8 on which I have a master and a node.  Weave runs on these giving me a pod network on 192.168.0.0/16.  When I launch jupyterhub on the metal on the master machine with kubespawner and the basic configs, it's confused because it's trying to access the 192 network:  
Failed to connect to http://192.168.96.1:8888/user/scott
but jupyterhub doesn't have access to that network.  
I found a few flags for jupyterhub that could be relevant: "ip", "proxy_api_ip" and "hub_ip", but I'm not super familiar with jupyterhub or kubernetes.  Any direction is appreciated.

**Comment by yuvipanda** [comment]
Heya!

Have you looked at https://github.com/jupyterhub/kubespawner/blob/master/SETUP.md? You need the `hub_connect_ip` of c.KubeSpawner.

Also we recommend running JupyterHub inside the kubernetes cluster, rather than outside.

**Comment by yuvipanda** [comment]
Would also suggest looking at z2jh.jupyter.org for deployment guides :)
