### ISSUE TITLE
maint: add `_` prefix to `load_user_options` and `delete_if_exists`

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/kubespawner#570]
I think these functions are private, lets mark them with a leading `_` to indicate that as part of going for a KubeSpawner v3 release with the changes in #563.

**Comment by manics** [comment]
Sounds fine to me, I think systematically adding `_` prefixes in all JupyterHub Python repos helps with maintenance. Probably something to bear in mind whenever new functions are added anywhere.
