### ISSUE TITLE
Avoid emitting warnings/errors during normal operation

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/kubespawner#578]
## Background

@athornton reports there are warnings/errors shown when using KubeSpawner that clutters logs. This issue is meant to help us dig into the details about that. My goal is to resolve it in a way within KubeSpawner that doesn't make us: risk suppressing a relevant warning/error, confuse an end user with irrelevant warnings/errors, maintain a fragile patch making changes to `aiohttp`.

## Technical details

We have switched the library we use to communicate with the k8s api-server to using [`kubernetes_asyncio`](https://github.com/tomplus/kubernetes_asyncio#readme) from [`kubernetes`](https://github.com/kubernetes-client/python#readme). When `kubernetes_asyncio` makes web requests, it uses [aiohttp](https://github.com/aio-libs/aiohttp#client).

- [`kubespawner` use `CoreV1Api` etc](https://github.com/jupyterhub/kubespawner/blob/main/kubespawner/spawner.py#L197) from `kubernetes_asycio`, via [the getter function `shared_client`](https://github.com/jupyterhub/kubespawner/blob/717e7ea65ef8780f0f5b693c35f5f03ada0ba8f8/kubespawner/clients.py#L54).
- [CoreV1Api use `RESTClientObject`](https://github.com/tomplus/kubernetes_asyncio/blob/0f7cb1658c97775fed0bb101b2a6ed225d35470a/kubernetes_asyncio/client/api_client.py#L75) from `aiohttp`
- [RESTClientObject use a `ClientSession` instance](https://github.com/tomplus/kubernetes_asyncio/blob/f028cc793e3a2c519be6a52a49fb77ff0b014c9b/kubernetes_asyncio/client/rest.py#L80-L82) from `aiohttp`.
- [ClientSession has a `__del__` destructor](https://github.com/aio-libs/aiohttp/blob/d01e257da9b37c35c68b3931026a2d918c271446/aiohttp/client.py#L295-L306) that emits warnings and that [raises errors (unsure about this)](https://github.com/aio-libs/aiohttp/blob/d01e257da9b37c35c68b3931026a2d918c271446/aiohttp/client.py#L306).

## Open questions about the warnings/errors

- _When_ do we see these errors when using KubeSpawner?
  - Is it only when we shut down a JupyterHub process?
  - Is it when we a user server?
  - Is it at all seemingly random times?
- _How_ do we see these errors when using KubeSpawner?
  - Is it via logs from the JupyterHub process?
  - How exactly does the logs look as reported from there?

## Open technical questions

- What options do we have?
  1. Patching `aiohttp`
  2. ???

## Related

- A strategy to supress warnings by patching `aiohttp` provided by @athornton in https://github.com/jupyterhub/kubespawner/issues/578.
- #563
- #576
- > The `__del__()` method is a known as a destructor method in Python. It is called when all references to the object have been deleted i.e when an object is garbage collected.
- > The [atexit](https://docs.python.org/3/library/atexit.html#module-atexit) module defines functions to register and unregister cleanup functions. Functions thus registered are automatically executed upon normal interpreter termination. [atexit](https://docs.python.org/3/library/atexit.html#module-atexit) runs these functions in the reverse order in which they were registered; if you register A, B, and C, at interpreter termination time they will be run in the order C, B, A.
  >
  >__Note__: The functions registered via this module are not called when the program is killed by a signal not handled by Python, when a Python fatal internal error is detected, or when [os._exit()](https://docs.python.org/3/library/os.html#os._exit) is called.

**Comment by minrk** [comment]
I dug into this a little bit, and it's because we allow our shared clients to be garbage collected by using weakrefs. If we held onto our shared_client objects and cleaned them up atexit instead, the warning appears to go away.

> that [raises errors (unsure about this)](https://github.com/aio-libs/aiohttp/blob/d01e257da9b37c35c68b3931026a2d918c271446/aiohttp/client.py#L306).

It doesn't raise errors (for us or by default). The loop's exception handler is the (overrideable) callback for unhandled errors in asyncio that don't have a coroutine/future to attach errors to. It _can_ be used to halt the loop if you want all errors to be fatal for some reason, but the default and most common behavior is to log and move on, which I think is why it's used here.

The feature that's really missing is an "atexit, but for asyncio" which is called when the event loop is closed. This doesn't exist, and there's no reliable way to register things (especially coroutines) to call at shutdown of asyncio while the eventloop still exists.

**Comment by consideRatio** [comment]
> I dug into this a little bit, and it's because we allow our shared clients to be garbage collected by using weakrefs. If we held onto our shared_client objects and cleaned them up atexit instead, the warning appears to go away.

Wieeeee I'm excited that you have a quite clear idea about the situation, I don't yet get it though!

1. clients.py defines `_client_cache = {}` where references are stored via `weakref.ref(client)` where the client instance was created in a function.
2. KubeSpawner instances are created over time that make use of shared clients...
3. KubeSpawner instances are garbage collected over time (I assume!)

Hmm... 
- JupyterHub terminates at some point
- atexit registered functions are called at some point
- the ClientSession aiohttp instances part of the shared clients gets called at some point, at which we get warnings/errors as we didn't terminate our clients properly first (??)

**Comment by manics** [comment]
I share @consideRatio's concerns about patching `aiohttp`, especially since it affects other JupyterHub components or extensions that might use `aiohttp`. Debugging async problems is already difficult enough!

Is it possible to come up with a test case we can add to https://github.com/jupyterhub/kubespawner/tree/main/tests so it's easy to reproduce?

**Comment by minrk** [comment]
#579 includes tests, but it patches asyncio instead of aiohttp! It patches it to do something good instead of skipping cleanup, though.

**Comment by athornton** [comment]
#579 seems like a good thing.  I'll withdraw the monkeypatch from the z2jh PR (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2594) and adopt #579 with a release that incorporates it.
