### ISSUE TITLE
Failing tests against JupyterHub 2.2.0

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/kubespawner#582]
Looking at the [JupyterHub changelog](https://github.com/jupyterhub/jupyterhub/blob/main/docs/source/changelog.md) i see https://github.com/jupyterhub/jupyterhub/pull/3810 and https://github.com/jupyterhub/jupyterhub/pull/3802 as candidates for what has changed and this KubeSpawner test fail.

I'm not sure if its problematic for proper function or not, but I'd like to investigate it before we can cut a release of KubeSpawner I think.

```python-traceback
tests/test_spawner.py::test_url_changed FAILED                           [ 90%]

=================================== FAILURES ===================================
_______________________________ test_url_changed _______________________________

kube_ns = 'kubespawner-test'
kube_client = <kubernetes_asyncio.client.api.core_v1_api.CoreV1Api object at 0x7f7c1e7ee9a0>
config = {'KubeSpawner': {'namespace': 'kubespawner-test', 'cmd': ['jupyterhub-singleuser'], 'start_timeout': 180, 'environment...cret-token', 'JUPYTERHUB_CLIENT_ID': 'ignored'}, 'pod_connect_ip': 'jupyter-{username}--{servername}.foo.example.com'}}
hub_pod = {'api_version': 'v1',
 'kind': 'Pod',
 'metadata': {'annotations': {'cni.projectcalico.org/podIP': '192.168.237.1[98](https://github.com/jupyterhub/kubespawner/runs/5496979939?check_suite_focus=true#step:6:98)/32...t',
            'reason': None,
            'start_time': datetime.datetime(2022, 3, 10, 14, 8, 15, tzinfo=tzlocal())}}
hub = <Hub 192.168.237.198:8081>

    async def test_url_changed(kube_ns, kube_client, config, hub_pod, hub):
        user = MockUser(name="url")
        config.KubeSpawner.pod_connect_ip = (
            "jupyter-{username}--{servername}.foo.example.com"
        )
        spawner = KubeSpawner(hub=hub, user=user, config=config)
        spawner.db = Mock()
    
        # start the spawner
        res = await spawner.start()
        pod_host = "http://jupyter-url.foo.example.com:8888/"
        assert res == pod_host
    
        # Mock an incorrect value in the db
        # Can occur e.g. by interrupting a launch with a hub restart
        # or possibly weird network things in kubernetes
        spawner.server = Server.from_url(res + "/users/url/")
>       spawner.server.ip = "1.2.3.4"
E       AttributeError: 'NoneType' object has no attribute 'ip'
```

**Comment by minrk** [comment]
It was https://github.com/jupyterhub/jupyterhub/pull/3810, which doesn't allow Spawner.server to be defined except in the db, like the mocks here. Fixed by https://github.com/jupyterhub/jupyterhub/pull/3819.

Can work around it by defining Spawner.orm_spawner, or we could mock less and create a real User object and real KubeSpawner via `spawner = user.spawners[""]` so that the instantiation is more realistic, as is done [in jupyterhub's own tests](https://github.com/jupyterhub/jupyterhub/blob/c23cddeb515dbcc0bc59c063ddba32d191624dcb/jupyterhub/tests/test_spawner.py#L51-L62).

**Comment by minrk** [comment]
We can also do a quick jupyterhub-2.2.1 tomorrow with https://github.com/jupyterhub/jupyterhub/pull/3819 so we don't have to worry about it.

**Comment by consideRatio** [comment]
Min resolved it all! As long as we don't test against JupyterHub 2.2.0, we are good - and if someone use 2.2.0 its fine for KubeSpawner as well, just not testing.
