### ISSUE TITLE
Support setting pod affinity

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/kubespawner#61]
Should allow us to 'pack' pods, making autoscalers' jobs easier.

**Comment by yuvipanda** [comment]
This would involve adding a traitlet to spawner that allows setting affinity & anti-affinity https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity

**Comment by consideRatio** [comment]
Pod affinity wasn't enough, but it will make an empty node remain empty, but if there are two nodes with one pod, the pods will keep spreading out.

Closing this as kubespawner can't do more than #239 and #222 to resolve user packing

**Comment by consideRatio** [comment]
Thanks @clkao for keeping things updated!!
