### ISSUE TITLE
Issues with IPv6 only cluster 

### ISSUE THREAD

**Issue by cbjhnsn** [jupyterhub/kubespawner#620]
When trying to start a user session on an IPv6 only EKS cluster the session fails with the error 

Spawn failed: Port could not be cast to integer value as '1f18:171d:402:7f94::1:8888'

It seems to be hanging up on the non-integer values in the IPv6 address. The prefix seems to be missing as well. The hub and CHP are running in IPv6 mode and seems to be working as expected. 

The user session pod does stay running and everything looks OK  

I've tried Kubespawner 3.0.2 and 4.1.0 with both Jupyterhub 1.5.0 and 2.3.1. EKS Cluster is 1.22 with the AWS VPC CNI.

**Comment by nikhiljha** [comment]
Hi! I ran into this issue earlier. It's fixed by https://github.com/jupyterhub/kubespawner/pull/619
