### ISSUE TITLE
Crash-loop when the the single user's PVC already exists and the K8s API takes more than 3s to reply

### ISSUE THREAD

**Issue by avsthiago** [jupyterhub/kubespawner#660]
### Bug description

Due to a misconfiguration of our OPA Gatekeeper, the k8s API was taking more that 3s to return a 409 error saying the PVC already exists, during the single user pod creation. Because of that, the kubespawner was constantly raising a [TimeoutError](https://github.com/jupyterhub/kubespawner/blob/main/kubespawner/spawner.py#L2540) instead of reporting a [ApiException](https://github.com/jupyterhub/kubespawner/blob/main/kubespawner/spawner.py#L2543), which would make the pod to spawn with no issues. 

Although this was an issue specific to our cluster, I think it would be nice to refactor the method [_make_create_pvc_request](https://github.com/jupyterhub/kubespawner/blob/main/kubespawner/spawner.py#L2519) and remove the possibility of this crash-loop to happen. Mostly because there are many other reasons for a k8s API to take longer to reply and because this issue is hard to debug (I wouldn't have understood the problem without looking into the kubespawner's code).

I'm willing to fix this issue, but I'd need some help from the maintainers to come up with a solution.

#### Expected behaviour
Even if it takes more than `k8s_api_request_timeout` for the k8s API to reply saying that the user's PVC already exists, the method [_make_create_pvc_request](https://github.com/jupyterhub/kubespawner/blob/main/kubespawner/spawner.py#L2519) should return True. 

#### Actual behaviour
When the k8s API takes longer than the [k8s_api_request_timeout](https://github.com/jupyterhub/kubespawner/blob/1.1.0/kubespawner/spawner.py#L287) (3s) to reply during the single user pod creation, and the user's PVC already exists, the JH Hub gets into a crash-loop.

### How to reproduce

As I mentioned, I only encountered this error because OPA Gatekeeper was improperly configured on our cluster. However, I think this error can be reproduced by reducing the value of the variable k8s_api_request_timeout to a value which will cause the TimeoutError to happen.

**Comment by dolfinus** [comment]
Why don't just increase `k8s_api_request_timeout` to `5s` or `10s`?

**Comment by avsthiago** [comment]
It got solved for us once we fixed gatekeeper. Increasing the timeout would also work, but  the crash-loop error could happen again if another issue which delays the API response pops up (I wouldn't blame the kubespawner in that case though)
