### ISSUE TITLE
extra VolumeClaims based on OpenID token claims

### ISSUE THREAD

**Issue by SGStino** [jupyterhub/kubespawner#675]
### Proposed change

Would it be possible to include custom volumes to a jupyter singleuser pod on spawn based on claims that were provided in the OAuth2 JWT token used to authenticate the user at the moment of spawning the pod?

### Alternative options

Can custom code be injected to the spawner via configmap so that this could be implemented on-demand?

### Who would use this feature?

Jupyterhub lets authenticate multiple users and each spin up their own instance, but there currently is, as far as i'm aware, no obvious way to share data between certain users/teams without creating a globally shared volume?

A few teams that used jupyter/jupyterhub all asked for that functionality, but I've never been able to give a solution.

### (Optional): Suggest a solution

Somehow find a way to encode the following automatically
```
    extraVolumes:
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: {{oidc_group_claim_value}}-shared-pvc
```
but for each value in the oidc_group_claim_value array. 

My best guess would be in:
https://github.com/jupyterhub/kubespawner/blob/0f22abf096459b5424325fa93ff4b30bef568391/kubespawner/spawner.py#L1856
and 
https://github.com/jupyterhub/kubespawner/blob/0f22abf096459b5424325fa93ff4b30bef568391/kubespawner/spawner.py#L1889

But because it's a multi-value expansion, the algorithm should change so it will be able to output multiple list-of-dict elements, one for each expanded oidc_group_claim_value.

But as how to get the claims in the spawner, i'm not sure yet. I can't seem to find the claims directly.

Alternatively, the groups could be used for this? But that could potentially interfere with other features that use groups (would require one volume per group, even if the group is only used for something else)

**Comment by consideRatio** [comment]
You can provide custom logic that can be using `auth_state` from the authenticator you have configured JupyterHub to rely on. How to do this is described in [this forum post](https://discourse.jupyter.org/t/tailoring-spawn-options-and-server-configuration-to-certain-users/8449#problem-2-adjust-spawned-server-config-based-on-user-andor-users-chosen-option-5) by using a `pre_spawn_hook`.

We have deliberated on providing a solution that doesn't require custom python code, but I think the needs are too general to cover by anything less than a dedicated hook to run arbitrary Python code.
