### ISSUE TITLE
Kubespawner fails to spawn singleuser POD

### ISSUE THREAD

**Issue by jbmarcille** [jupyterhub/kubespawner#68]
I have been testing the kubespawner for a few weeks now and recently switched to the current master branch. Since then, I am unable to spawn the singleuser POD while this worked with a previous version of the kubespawner with Jupyterhub 0.7.2 (bare metal cluster with Kubernetes 1.5.2).

The working kubespawner version used: **_httpclient_** + **_k8s_url_**
while the new version uses the kubernetes python-client **_CoreV1Api_** directly.

The logs showed that the claim request actually works:

`header: Content-Type header: Date header: Transfer-Encoding send: b'POST /api/v1/namespaces/notebook/persistentvolumeclaims HTTP/1.1\r\nHost: 10.10.10.1\r\nAccept-Encoding: identity\r\nContent-Length: 368\r\nAccept: application/json\r\nauthorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6Ik...\r\nContent-Type: application/json\r\nUser-Agent: Swagger-Codegen/1.0.0-snapshot/python\r\n\r\n'
send: b'{"spec": {"resources": {"requests": {"storage": "1Gi"}}, "accessModes": ["ReadWriteMany"]}, "apiVersion": "v1", "metadata": {"labels": {"heritage": "jupyterhub", "hub.jupyter.org/username": "toto", "app": "jupyterhub"}, "name": "pvcjupyterhub-singleuser", "annotations": {"volume.beta.kubernetes.io/storage-class": "glusterfs"}}, "kind": "PersistentVolumeClaim"}'
reply: 'HTTP/1.1 409 Conflict\r\n'`

The code I added to retrieve the jupyterhub accessible IP from the service name also works:

`header: Content-Type header: Date header: Content-Length send: b'GET /api/v1/namespaces/notebook/services/jupyterhub?exact=True&export=False HTTP/1.1\r\nHost: 10.10.10.1\r\nAccept-Encoding: identity\r\nAccept: application/json\r\nauthorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...\r\nContent-Type: application/json\r\nUser-Agent: Swagger-Codegen/1.0.0-snapshot/python\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'`

The request to kubernetes to create the POD times out:

`header: Content-Type header: Date header: Content-Length send: b'POST /api/v1/namespaces/notebook/pods HTTP/1.1\r\nHost: 10.10.10.1\r\nAccept-Encoding: identity\r\nContent-Length: 1676\r\nAccept: application/json\r\nauthorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9....\r\nContent-Type: application/json\r\nUser-Agent: Swagger-Codegen/1.0.0-snapshot/python\r\n\r\n'
/opt/conda/lib/python3.5/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2017-07-28 07:15:50,705 DEBUG https://10.10.10.1:443 "POST /api/v1/namespaces/notebook/pods HTTP/1.1" 201 1965
DEBUG:urllib3.connectionpool:https://10.10.10.1:443 "POST /api/v1/namespaces/notebook/pods HTTP/1.1" 201 1965`

```
[W 2017-07-28 07:16:00.552 JupyterHub base:336] User toto's server is slow to start (timeout=10)
[W 2017-07-28 07:20:50.552 JupyterHub user:246] toto's server failed to start in 300 seconds, giving up
[E 2017-07-28 07:20:50.614 JupyterHub gen:878] Exception in Future <tornado.concurrent.Future object at 0x7fd6b44f9898> after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 874, in error_callback
        future.result()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 261, in spawn
        raise e
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 229, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
    tornado.gen.TimeoutError: Timeout
```
At this point I'm not sure what goes wrong so if you have any clue on this that will help.

**Comment by minrk** [comment]
Should be fixed by #174
