### ISSUE TITLE
Interacting with a profile_list's nested server options should select the server

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/kubespawner#696]
@jbusecke reported this experience, and I think it makes for a good improvement of KubeSpawner's `profile_list` `profile_options` feature.

>Currently I can select an image on e.g. the medium server, but the default radio button selection will still be on a small server. 
>
>I think it would make a lot of sense to automatically select whichever instance the drop down is attached to, once the drop down is selected?

Each entry in the `profile_list` can have additional options as configured under the `profile_list` list entry's `profile_options`. Interaction with such options should switch the radio button to select the `profile_list` entry having those `profile_options`.

![profile-list-option](https://user-images.githubusercontent.com/3837114/216133003-d3f346d8-45ab-4381-a947-9fcc108fea6f.gif)

**Comment by jbusecke** [comment]
All credit for raising this goes to @RobertPincus 😀
