### ISSUE TITLE
Username issues with usernames that are subsets of other usernames

### ISSUE THREAD

**Issue by zogren** [jupyterhub/kubespawner#71]
Not 100% sure this is an issue with the spawner but if a pod is spun up with username test1 then one with name test11 can not be created (the system acts like it already exists and redirects to a 404 page)

I tested this with various names and it seems to always be an issue if a username pod already exists and the new pod starts with the existing name. Guessing its an issue with some lookup for the pod name.

**Comment by consideRatio** [comment]
Since this issue wasn't followed up by the author, I'll close it now. I have not experience anything like this so far.
