### ISSUE TITLE
Allow spawning a namespace per user

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/kubespawner#76]
Right now we use one namespace for all user pods. It'll be great to allow spawning one namespace per user, so users can do additional things in their namespaces (like spawning other clusters)

**Comment by yuvipanda** [comment]
The biggest problem here is that our reflector only watches one namespace. Should we have multiple watchers? Multiple kinds of watchers? 

Perhaps we need a kind of SharedInformer design that lets us hold multiple watchers? Don't want to have one watcher per pod.

**Comment by zflamig** [comment]
Is anyone working on this currently? It would be a great feature to have...

**Comment by viroos** [comment]
I will be also interested in having this feature.

**Comment by agt-ucsd** [comment]
I'm looking to integrate JupyterHub into an existing k8s cluster which utilizes a large number (>1000) of per-user namespaces.  

As discussed in #79 , templating Namespace seems like a reasonable approach.  Our namespaces are provisioned externally; would anyone object to deferring ns creation/cleanup to a future enhancement?

**Comment by zflamig** [comment]
Based on @yuvipanda's comment, I think those would actually be separate enhancements anyways @agt-ucsd? I think this PR handles the creation/cleanup and then we need to develop a separate one which handles the watching multiple namespaces which is the thing you want?

**Comment by agt-ucsd** [comment]
@zflamig  thanks, it sounds like you're in agreement that creation/cleanup of per-user namespaces is separable from generic support for multiple user namespaces (which besides converting namespace to a template/callable, would also entail changes to watching).    I'll open a separate issue for the latter.

**Comment by SolarisYan** [comment]
@yuvipanda 
Hi all, How is this feature going?

**Comment by lresende** [comment]
I believe this has been fixed by #458
