### ISSUE TITLE
KubeSpawner `latest` docs is missing some traitlets help

### ISSUE THREAD

**Issue by manics** [jupyterhub/kubespawner#788]
### Bug description

Compare the traitlets help documentation in stable (6.0.0)
https://jupyterhub-kubespawner.readthedocs.io/en/stable/spawner.html#kubespawner.KubeSpawner.extra_pod_config
![image](https://github.com/jupyterhub/kubespawner/assets/1644105/ba23b171-31c5-40a0-abaa-42e76bc28137)

with latest which has `No help string is provided` for some traitlets:
https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner.extra_pod_config
![image](https://github.com/jupyterhub/kubespawner/assets/1644105/aa3e6d79-1767-48b4-b71c-8c4d569efd48)

### How to reproduce

https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner.extra_pod_config

#### Expected behaviour

https://jupyterhub-kubespawner.readthedocs.io/en/stable/spawner.html#kubespawner.KubeSpawner.extra_pod_config / https://jupyterhub-kubespawner.readthedocs.io/en/6.0.0/spawner.html#kubespawner.KubeSpawner.extra_pod_config
has help messages for the traitlets

#### Actual behaviour

`No help string is provided` for some traitlets

**Comment by consideRatio** [comment]
This isn't a KubeSpawner specific issue, it happens in dask/dask-gateway as well

**Comment by consideRatio** [comment]
There is a pattern to what help strings are missing - all config with the type Dict, List, Command. The underlying pattern for this could be that they relate to reference type and not value type variables perhaps.
- Dict
- List
- Command

**Comment by consideRatio** [comment]
Ah, and further, its an issue reproducing with traitlets 5.10.0, but not 5.9.0.
