### ISSUE TITLE
Doc blocks contain dead links to kubernetes API v1.20

### ISSUE THREAD

**Issue by acjbrouwer** [jupyterhub/kubespawner#794]
### Doc blocks contain dead links to kubernetes API v1.20

For example the dict and help for [`extra_pod_config` as defined in `spawner.py` at line 1281](https://github.com/jupyterhub/kubespawner/blob/6d9d9a36df3077b6ba22e4a94107ffe96fc2b18c/kubespawner/spawner.py#L1281) links to `https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#<something something>` as is the case for a few [other bits of documentation throughout the repo](https://github.com/search?q=repo%3Ajupyterhub%2Fkubespawner+%22kubernetes-api%2Fv1.20%22&type=code). The target page is no longer extant.

### How to reproduce

1. Go to the [`extra_pod_config` documentation](https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner.extra_pod_config)
2. Click on the link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#podspec-v1-core
3. ⇒ 404 Page not found

**Comment by manics** [comment]
I think we just need to replace `v1.20` with a more recent version like `v1.26`. I'm surprised Kubernetes don't keep their old API docs though, especially since the version is part of the URL so there' are no conflicts.

**Comment by consideRatio** [comment]
Go for k8s 1.28 if updating this, its the latest
