### ISSUE TITLE
ReadTheDocs for Kubespawner appears to be duplicating various items (PDF and epub)

### ISSUE THREAD

**Issue by Analect** [jupyterhub/kubespawner#80]
@yuvipanda @willingc 

I was running through the kubespawner docs today, reacquainting myself with some changes (new features) introduced since I last looked at it earlier this year.  I notice that under the 'v:latest' [Spawners section](http://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#module-kubespawner.spawner), many of the `config` settings are repeated unnecessarily, leading to some bloat in section 4.3 (if you generate the PDF).  So, for example, from the link above, if you search for `config c.KubeSpawner.cmd = Command()`, you'll find two entries in the docs.  Not sure if this is meant by design or not.

From the PDF version (below), various config items described on pages 7/8 of the PDF are repeated on page 15.  I'm just showing a few here ... I took a look at the `/docs` folder in the repo, but I'm not familiar enough with the readthedocs protocol to fix this ... if indeed it is an error.  Just thought I'd flag it to you.

![image](https://user-images.githubusercontent.com/4063815/30070422-401672ec-925b-11e7-81f6-7f01b4fc869a.png)

**Comment by consideRatio** [comment]
I noticed this also!

@Analect I like your communication, a lot of nice images etc in general :D

**Comment by willingc** [comment]
Thanks all. This is a bug with PDF generation and ePub generation. The duplication is not found on the online version of the docs.

**Comment by consideRatio** [comment]
If i visit this link
http://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#module-kubespawner.spawner

And search for
config c.KubeSpawner.extra_resource_guarantees = Dict()

I'll find duplicated entries. It is the same with very  many entries, like 80% of them.

**Comment by willingc** [comment]
Hi @consideRatio, 

Weird. I just tried your suggestion and this is the result that I am seeing:

<img width="1279" alt="screenshot 2018-01-03 07 42 01" src="https://user-images.githubusercontent.com/2680980/34527275-e9ca5270-f059-11e7-918b-5924b74fe8ff.png">

What revision of the documentation is your system displaying? It should display the latest commit hash: 5c9bf387. If not, would you mind reloading or clearing your cache and see if it still exists?

If it does have that commit, what browser and os are you using?

**Comment by consideRatio** [comment]
@willingc sorry for the confusion I meant a `CTRL+F` kind of search!

Replication:
1. Visit http://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html
2. Search within page (`CTRL+F` or similar) for `config c.KubeSpawner.extra_resource_guarantees = Dict()`
