### ISSUE TITLE
The server should be self.server to work with 0.8 hub instead of self.user.server

### ISSUE THREAD

**Issue by Analect** [jupyterhub/kubespawner#82]
Adding based on an interaction with @minrk on the jupyterhub slack channel [here](https://gitter.im/jupyterhub/jupyterhub?at=59bbd6e0614889d475ffe6fc).

It was in the context of testing launching a named-server using the `0.5.x branch` of zero-to-jupyterhub set-up (ie. on kubernetes).

I had previously been testing against `/hub/api/users/:user/server/:server_name` instead of `/hub/api/users/:user/servers/:server_name` (ie. missing an 's').

Now running this, I still get a `500 error`, as per these [logs](https://gist.github.com/Analect/f678ba8edd527d9129ab083b9fabbc21), which complains about a missing `JPY_COOKIE_NAME`, which, as per @minrk relates to the `get_env` method [here](https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L847-L858), which he suggests should get removed and that I see has been marked as deprecated.

In the interim, to get around this, is it enough to add something like this to the config.yaml in the helm-chart, or would that only partly-solve things?

```
hub
  extraEnv:
    JPY_COOKIE_NAME: 'hub-secret'
```

**Comment by minrk** [comment]
> In the interim, to get around this, is it enough to add something like this to the config.yaml in the helm-chart, or would that only partly-solve things?

I don't believe that will work. I think KubeSpawner needs to be updated to either reflect that these have moved, or more likely to remove it since it's a backward-compatibility workaround for old images.

**Comment by Analect** [comment]
@yuvipanda 
With [this](https://github.com/Analect/kubespawner/commit/a7cadf382327a62b899e503f7c5fdab1e5672114) change to kubespawner, I was able to start a named-server for user 'mcoole' as follows:

`curl -v -X POST -H "Authorization: token 1f9aa148e09141b8b1d869f7995bdda2" "http://myjupyterhub.com/hub/api/users/mccoole/servers/test1"`

and with this running, then ran another:
`curl -v -X POST -H "Authorization: token 1f9aa148e09141b8b1d869f7995bdda2" "http://myjupyterhub.com/hub/api/users/mccoole/servers/test2"`

Obviously kube-spawner is currently set up to name a pod according to the `jupyter-{username}` and so both servers has the same non-unique name and hence, as per the logs below, starting the second server kills the first pod.

I can see that I need to rename the pod (and potentially the PVC) such that it uses something like `jupyter-{username}-{servername}`, so that it creates pods `jupyter-mccoole-test1` and `jupyter-mccoole-test2`.

I can see from the spawner.py on jupyterhub, that `self.name` is the named-server name ... as in [here](
https://github.com/jupyterhub/jupyterhub/blob/0e7ccb75208c551908028788c859e0ac445141f1/jupyterhub/spawner.py#L554) ... I'm just wondering if that is accessible within the kubespawner/spawner.py [here](https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L45-L75), in terms of me being able to access the value for `self.name` and assign it to something like `servername`

Something like:
```
if self.name:
    servername = self.name
```

hub logs on trying to start simultaneous named servers for a user:
```
[I 2017-09-18 20:54:23.252 JupyterHub spawner:766] PVC claim-mccoole already exists, so did not create new pvc.
[W 2017-09-18 20:54:33.246 JupyterHub base:482] User mccoole:test1 is slow to start (timeout=10)
[I 2017-09-18 20:54:33.249 JupyterHub log:122] 202 POST /hub/api/users/mccoole/servers/test1 (mccoole@10.132.0.5) 10062.11ms
[I 2017-09-18 20:54:33.577 JupyterHub log:122] 200 GET /hub/api (@10.4.4.226) 0.69ms
[I 2017-09-18 20:54:34.307 JupyterHub base:446] User mccoole:test1 took 11.117 seconds to start
[I 2017-09-18 20:54:34.309 JupyterHub proxy:231] Adding user mccoole to proxy /user/mccoole/test1/ => http://10.4.4.226:8888
[I 2017-09-18 20:54:45.300 JupyterHub log:122] 200 GET /hub/admin (mccoole@10.4.4.1) 6.71ms
[I 2017-09-18 20:55:37.873 JupyterHub log:122] 302 GET /hub/api/oauth2/authorize?redirect_uri=%2Fuser%2Fmccoole%2Ftest1%2Foauth_callback&client_id=user-mccoole-test1&response_type=code \u2192 /user/mccoole/test1/oauth_callback?code=51e97f25-4f6f-4b45-9588-48c74a51bd31 (mccoole@10.4.4.1) 9.11ms
[I 2017-09-18 20:55:37.938 JupyterHub log:122] 200 POST /hub/api/oauth2/token (mccoole@10.4.4.226) 20.29ms
[I 2017-09-18 20:55:37.947 JupyterHub log:122] 200 GET /hub/api/authorizations/token/[secret] (mccoole@10.4.4.226) 5.79ms
[I 2017-09-18 20:55:38.029 JupyterHub log:122] 200 GET /hub/api/authorizations/token/[secret] (mccoole@10.4.4.226) 5.39ms
[I 2017-09-18 20:56:36.695 JupyterHub spawner:766] PVC claim-mccoole already exists, so did not create new pvc.
[I 2017-09-18 20:56:36.706 JupyterHub spawner:789] Found existing pod jupyter-mccoole, attempting to kill
[I 2017-09-18 20:56:37.722 JupyterHub spawner:792] Killed pod jupyter-mccoole, will try starting singleuser pod again
[I 2017-09-18 20:56:40.071 JupyterHub log:122] 200 GET /hub/api (@10.4.4.227) 0.68ms
[I 2017-09-18 20:56:40.751 JupyterHub base:446] User mccoole:test2 took 4.099 seconds to start
[I 2017-09-18 20:56:40.753 JupyterHub proxy:231] Adding user mccoole to proxy /user/mccoole/test2/ => http://10.4.4.227:8888
[I 2017-09-18 20:56:40.760 JupyterHub log:122] 201 POST /hub/api/users/mccoole/servers/test2 (mccoole@10.132.0.5) 4121.11ms
[I 2017-09-18 20:56:55.319 JupyterHub log:122] 302 GET /hub/api/oauth2/authorize?redirect_uri=%2Fuser%2Fmccoole%2Ftest2%2Foauth_callback&response_type=code&client_id=user-mccoole-test2 \u2192 /user/mccoole/test2/oauth_callback?code=a1fbe0af-6353-4b15-b015-ef4212f03841 (mccoole@10.132.0.2) 9.25ms
[I 2017-09-18 20:56:55.390 JupyterHub log:122] 200 POST /hub/api/oauth2/token (mccoole@10.4.4.227) 27.49ms
[I 2017-09-18 20:56:55.401 JupyterHub log:122] 200 GET /hub/api/authorizations/token/[secret] (mccoole@10.4.4.227) 6.87ms
[I 2017-09-18 20:56:55.476 JupyterHub log:122] 200 GET /hub/api/authorizations/token/[secret] (mccoole@10.4.4.227) 4.26ms
[I 2017-09-18 20:57:04.461 JupyterHub log:122] 302 GET /503?url=%2Fuser%2Fmccoole%2Ftest1%2Fapi%2Fsessions%3F_%3D1505768138287 \u2192 /hub/503?url=%2Fuser%2Fmccoole%2Ftest1%2Fapi%2Fsessions%3F_%3D1505768138287 (@10.4.4.217) 0.64ms
[I 2017-09-18 20:57:04.462 JupyterHub log:122] 302 GET /503?url=%2Fuser%2Fmccoole%2Ftest1%2Fapi%2Fterminals%3F_%3D1505768138288 \u2192 /hub/503?url=%2Fuser%2Fmccoole%2Ftest1%2Fapi%2Fterminals%3F_%3D1505768138288 (@10.4.4.217) 0.41ms
[I 2017-09-18 20:57:14.366 JupyterHub log:122] 302 GET /503?url=%2Fuser%2Fmccoole%2Ftest1%2Ftree%3F \u2192 /hub/503?url=%2Fuser%2Fmccoole%2Ftest1%2Ftree%3F (@10.4.4.217) 0.72ms
[I 2017-09-18 20:57:14.367 JupyterHub log:122] 302 GET /503?url=%2Fuser%2Fmccoole%2Ftest1%2Fapi%2Fsessions%3F_%3D1505768138289 \u2192 /hub/503?url=%2Fuser%2Fmccoole%2Ftest1%2Fapi%2Fsessions%3F_%3D1505768138289 (@10.4.4.217) 0.43ms
[I 2017-09-18 20:57:14.368 JupyterHub log:122] 302 GET /503?url=%2Fuser%2Fmccoole%2Ftest1%2Fapi%2Fterminals%3F_%3D1505768138290 \u2192 /hub/503?url=%2Fuser%2Fmccoole%2Ftest1%2Fapi%2Fterminals%3F_%3D1505768138290 (@10.4.4.217) 0.62ms
```
What are your thoughts?

**Comment by Analect** [comment]
see https://github.com/jupyterhub/kubespawner/pull/83
