### ISSUE TITLE
Cannot build wheel for package due to folder name being different to package name

### ISSUE THREAD

**Issue by willh-cmyk** [jupyterhub/kubespawner#831]
### Bug description

I'm getting this error when building wheels for my multistage docker build:

```
ValueError: Unable to determine which files to ship inside the wheel using the following heuristics: https://hatch.pypa.io/latest/plugins/builder/wheel/#default-file-selection

The most likely cause of this is that there is no directory that matches the name of your project (jupyterhub_kubespawner).

At least one file selection option must be defined in the `tool.hatch.build.targets.wheel` table, see: https://hatch.pypa.io/latest/config/build/

As an example, if you intend to ship a directory named `foo` that resides within a `src` directory located at the root of your project, you can define the following:

[tool.hatch.build.targets.wheel]
packages = ["src/foo"]
```

### How to reproduce

Run the following:

```bash
pip wheel -- no-binary :all: --no-deps --wheel-dir=/tmp/wheels jupyterhub_kubespawner==6.2.0
```

#### Expected behaviour

The wheel to build successfully and the `.whl` file to be written to `/tmp/wheels`.

#### Actual behaviour

The command fails because the package name is different to the folder name. The package name is `jupyterhub_kubespawner` and the folder name is `kubespawner`.

### Your personal set up

 - OS:
 
 - Version(s): Ubuntu 22.04.4
 
Jupyterhub:
- Version(s): 4.1.5

Python:
- Version(s): 3.11.5

<details><summary>Full environment</summary>

I can't provide this information.

**Comment by consideRatio** [comment]
@willh-cmyk thank you!!! :heart: :tada:
