### ISSUE TITLE
periodic reflector health check

### ISSUE THREAD

**Issue by minrk** [jupyterhub/kubespawner#85]
We've seen a few cases where the reflector started missing events. We should probably have a periodic re-sync to make sure that the reflector is alive and well and in-sync with Kubernetes. While #81 fixes one known race condition, I suspect that there are other ways for events to be missed.

**Comment by yuvipanda** [comment]
@minrk how do you think we should make this happen now? Also do you think we still need to do this despite the resourceversion patch you landed?

**Comment by minrk** [comment]
I think this might still be worthwhile, but I have a lot more confidence after the resourceversion change, so I would call this a low priority until we see another potential symptom of missed events.

As we've seen with `Proxy.check_routes`, periodic sanity checks in an async world are nontrivial.

**Comment by minrk** [comment]
#174 adds timeouts, which ought to be good enough
