### ISSUE TITLE
Never orphan pods

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/kubespawner#95]
Right now, if we start a pod but it doesn't successfully launch in the launch timeout, we just sort of let it exist forever, in an orphaned state. This is very problematic!

We should make sure we clean up after ourselves if we do not launch in time.

**Comment by yuvipanda** [comment]
You can repro this by doing something like having a wrong image name in the config or an image that takes longer to download than the configured timeout. It will make it impossible for the user to launch until the pod is manually deleted.

**Comment by consideRatio** [comment]
I think this is a resolved issue, I have not seen us orphan pods for a long time.
