### ISSUE TITLE
Long user names used in pod and pvc labels not allowed by k8s

### ISSUE THREAD

**Issue by enolfc** [jupyterhub/kubespawner#97]
The `hub.jupyter.org/username` label in pod or pvc manifests (e.g. https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L663) when user name has more than 63 characters will make the creation of the pod fail with a error like this:

error: invalid label value: "hub.jupyter.org/username=notebook-a8e986f5974c1ee896fa7717cad98511be0388b3d667535d9af7fe18feab7e3d": must be no more than 63 characters

The username I'm using comes from an external OAuth2 IdP and has a fixed length of 64 characters so any pod creation will  always fail. As a workaround I have changed the label to `hub.jupyter.org/userid` and use the id which should be small enough. However I'm not sure if that's the right approach.

**Comment by betatim** [comment]
Another idea is to compute a hash from the original name and then use only N characters of the hash. This is what [binderhub does](https://github.com/jupyterhub/binderhub/blob/044c8c2789aac016effcfbc75a7844e149d310a3/binderhub/builder.py#L114)

It would probably be a good idea for kubespawner to have a way to deal with names which are too long.

**Comment by yuvipanda** [comment]
Yeah, I think lifting the code from BinderHub to here makes sense...

**Comment by yuvipanda** [comment]
This is also problematic for users with _s and what not in their names. I think we should / could put the unfiltered name as an annotation and stop putting user labels.
