### ISSUE TITLE
extra_containes instead of extra_containers in make_pod call.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jupyterhub/kubespawner#99]
Line:

* https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L771

has:

```
            extra_containes=self.singleuser_extra_containers
```

That will surely die as keyword argument of ``make_pod`` is ``extra_containers``.

**Comment by yuvipanda** [comment]
Thanks for the catch, @GrahamDumpleton! I've made a PR to fix it!
